<?php


/**
 * This class adds structure of 'c002t_informe_forense' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Nov 14 07:33:31 2015
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class C002tInformeForenseMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.C002tInformeForenseMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(C002tInformeForensePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(C002tInformeForensePeer::TABLE_NAME);
		$tMap->setPhpName('C002tInformeForense');
		$tMap->setClassname('C002tInformeForense');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('c002t_informe_forense_co_informe_forense_seq');

		$tMap->addPrimaryKey('CO_INFORME_FORENSE', 'CoInformeForense', 'BIGINT', true, null);

		$tMap->addForeignKey('CO_REGION', 'CoRegion', 'BIGINT', 'j813t_region', 'CO_REGION', true, null);

		$tMap->addForeignKey('CO_NEGOCIO', 'CoNegocio', 'BIGINT', 'j814t_negocio', 'CO_NEGOCIO', true, null);

		$tMap->addForeignKey('CO_DIVISION', 'CoDivision', 'BIGINT', 'j815t_division', 'CO_DIVISION', true, null);

		$tMap->addForeignKey('CO_ESTADO_INFORME', 'CoEstadoInforme', 'BIGINT', 'j803t_estado_informe', 'CO_ESTADO_INFORME', true, null);

		$tMap->addColumn('TX_SERIAL', 'TxSerial', 'VARCHAR', false, 255);

		$tMap->addColumn('TX_TITULO', 'TxTitulo', 'VARCHAR', true, 255);

		$tMap->addColumn('TX_DESCRIPCION_ENTORNO', 'TxDescripcionEntorno', 'LONGVARCHAR', false, null);

		$tMap->addColumn('TX_RESULTADOS', 'TxResultados', 'LONGVARCHAR', false, null);

		$tMap->addColumn('TX_CONCLUSIONES', 'TxConclusiones', 'LONGVARCHAR', false, null);

		$tMap->addColumn('TX_OBSERVACIONES', 'TxObservaciones', 'VARCHAR', false, 255);

		$tMap->addColumn('TX_RUTA_PDF', 'TxRutaPdf', 'VARCHAR', false, 255);

		$tMap->addColumn('NB_ARCHIVO_PDF', 'NbArchivoPdf', 'VARCHAR', false, 255);

		$tMap->addForeignKey('CO_TRANSACCION', 'CoTransaccion', 'BIGINT', 'c801t_transaccion', 'CO_TRANSACCION', true, null);

		$tMap->addForeignKey('CO_CLASIFICACION', 'CoClasificacion', 'BIGINT', 'j802t_clasificacion', 'CO_CLASIFICACION', true, null);

		$tMap->addColumn('IN_ABIERTO', 'InAbierto', 'BOOLEAN', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATE_AT', 'UpdateAt', 'TIMESTAMP', false, null);

		$tMap->addForeignKey('CO_FORENSE', 'CoForense', 'BIGINT', 'c001t_forense', 'CO_FORENSE', true, null);

		$tMap->addColumn('NB_ARCHIVO_SOPORTE', 'NbArchivoSoporte', 'VARCHAR', false, 255);

		$tMap->addColumn('TX_RUTA_SOPORTE', 'TxRutaSoporte', 'VARCHAR', false, 255);

	} // doBuild()

} // C002tInformeForenseMapBuilder
