<?php


/**
 * This class adds structure of 'c140t_depuracion' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Nov 14 07:33:32 2015
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class C140tDepuracionMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.C140tDepuracionMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(C140tDepuracionPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(C140tDepuracionPeer::TABLE_NAME);
		$tMap->setPhpName('C140tDepuracion');
		$tMap->setClassname('C140tDepuracion');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('c140t_depuracion_co_depuracion_seq');

		$tMap->addPrimaryKey('CO_DEPURACION', 'CoDepuracion', 'BIGINT', true, null);

		$tMap->addColumn('CO_REGION', 'CoRegion', 'INTEGER', true, null);

		$tMap->addColumn('CO_NEGOCIO', 'CoNegocio', 'INTEGER', true, null);

		$tMap->addColumn('CO_DIVISION', 'CoDivision', 'INTEGER', true, null);

		$tMap->addColumn('CO_TIPO_DEPURACION', 'CoTipoDepuracion', 'INTEGER', true, null);

		$tMap->addColumn('CO_EQUIPO', 'CoEquipo', 'INTEGER', true, null);

		$tMap->addColumn('CO_SISTEMA', 'CoSistema', 'INTEGER', true, null);

		$tMap->addColumn('CO_ESTADO_DEPURACION', 'CoEstadoDepuracion', 'INTEGER', true, null);

		$tMap->addColumn('FE_MES_PLANIFICADO', 'FeMesPlanificado', 'DATE', false, null);

		$tMap->addColumn('TX_SERIAL_DEPURACION', 'TxSerialDepuracion', 'VARCHAR', false, 255);

		$tMap->addColumn('FE_DEPURACION', 'FeDepuracion', 'DATE', false, null);

		$tMap->addColumn('TX_INDICADOR_RESPONSABLE', 'TxIndicadorResponsable', 'VARCHAR', false, 255);

		$tMap->addColumn('TX_RESUMEN', 'TxResumen', 'LONGVARCHAR', false, null);

		$tMap->addColumn('NU_TOTAL_ACCESOS', 'NuTotalAccesos', 'NUMERIC', false, null);

		$tMap->addColumn('NU_TOTAL_DEPURACION', 'NuTotalDepuracion', 'NUMERIC', false, null);

		$tMap->addColumn('TX_OBSERVACIONES', 'TxObservaciones', 'LONGVARCHAR', false, null);

		$tMap->addColumn('CO_CLASIFICACION', 'CoClasificacion', 'INTEGER', false, null);

		$tMap->addColumn('NB_ANEXOS_SOPORTE', 'NbAnexosSoporte', 'VARCHAR', false, 255);

		$tMap->addColumn('TX_RUTA_ANEXO_SOPORTE', 'TxRutaAnexoSoporte', 'VARCHAR', false, 255);

		$tMap->addColumn('NB_ANEXOS_INFORME', 'NbAnexosInforme', 'VARCHAR', false, 255);

		$tMap->addColumn('TX_RUTA_ANEXO_INFORME', 'TxRutaAnexoInforme', 'VARCHAR', false, 255);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'DATE', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'DATE', false, null);

		$tMap->addColumn('CO_TRANSACCION', 'CoTransaccion', 'INTEGER', false, null);

		$tMap->addColumn('AR_ANEXO_SOPORTE', 'ArAnexoSoporte', 'BLOB', false, null);

		$tMap->addColumn('MIME_ANEXO_SOPORTE', 'MimeAnexoSoporte', 'VARCHAR', false, 255);

	} // doBuild()

} // C140tDepuracionMapBuilder
