<?php


/**
 * This class adds structure of 'c803t_accion' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Nov 14 07:33:32 2015
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class C803tAccionMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.C803tAccionMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(C803tAccionPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(C803tAccionPeer::TABLE_NAME);
		$tMap->setPhpName('C803tAccion');
		$tMap->setClassname('C803tAccion');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('c803t_accion_co_accion_seq');

		$tMap->addColumn('CO_ACCION', 'CoAccion', 'BIGINT', true, null);

		$tMap->addColumn('CO_TRANSACCION', 'CoTransaccion', 'BIGINT', false, null);

		$tMap->addColumn('TX_DESCRIPCION', 'TxDescripcion', 'VARCHAR', false, 255);

		$tMap->addColumn('CO_TIPO_CONTROL', 'CoTipoControl', 'BIGINT', false, null);

		$tMap->addColumn('CO_CATEGORIA_ACCION', 'CoCategoriaAccion', 'VARCHAR', false, 255);

		$tMap->addColumn('IN_ABIERTO', 'InAbierto', 'BOOLEAN', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATE_AT', 'UpdateAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('CO_CREATED_AT', 'CoCreatedAt', 'BIGINT', false, null);

		$tMap->addColumn('CO_UPDATED_AT', 'CoUpdatedAt', 'BIGINT', false, null);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

	} // doBuild()

} // C803tAccionMapBuilder
