<?php


/**
 * This class adds structure of 'c805t_rel_transaccion_principio' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Nov 14 07:33:32 2015
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class C805tRelTransaccionPrincipioMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.C805tRelTransaccionPrincipioMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(C805tRelTransaccionPrincipioPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(C805tRelTransaccionPrincipioPeer::TABLE_NAME);
		$tMap->setPhpName('C805tRelTransaccionPrincipio');
		$tMap->setClassname('C805tRelTransaccionPrincipio');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('c805t_rel_transaccion_principio_co_relacion_seq');

		$tMap->addPrimaryKey('CO_RELACION', 'CoRelacion', 'BIGINT', true, null);

		$tMap->addForeignKey('CO_TRANSACCION', 'CoTransaccion', 'BIGINT', 'c002t_informe_forense', 'CO_INFORME_FORENSE', false, null);

		$tMap->addForeignKey('CO_PRINCIPIO', 'CoPrincipio', 'BIGINT', 'j801t_principio', 'CO_PRINCIPIO', false, null);

	} // doBuild()

} // C805tRelTransaccionPrincipioMapBuilder
