<?php


/**
 * This class adds structure of 'j062_interfaces' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Nov 14 07:33:32 2015
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class J062InterfacesMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.J062InterfacesMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(J062InterfacesPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(J062InterfacesPeer::TABLE_NAME);
		$tMap->setPhpName('J062Interfaces');
		$tMap->setClassname('J062Interfaces');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('j062_interfaces_co_interfaz_seq');

		$tMap->addColumn('CO_INTERFAZ', 'CoInterfaz', 'BIGINT', true, null);

		$tMap->addColumn('TX_NOMBRE_INTERFAZ', 'TxNombreInterfaz', 'VARCHAR', true, 255);

		$tMap->addColumn('TX_IP', 'TxIp', 'VARCHAR', true, 255);

		$tMap->addColumn('TX_MAC', 'TxMac', 'VARCHAR', true, 255);

		$tMap->addColumn('CO_EQUIPO', 'CoEquipo', 'BIGINT', true, null);

		$tMap->addColumn('CO_EQUIPO_CONECTADO', 'CoEquipoConectado', 'BIGINT', true, null);

		$tMap->addColumn('TX_OBSERVACIONES', 'TxObservaciones', 'VARCHAR', false, 255);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

	} // doBuild()

} // J062InterfacesMapBuilder
