<?php


/**
 * This class adds structure of 'j142t_estado_depuracion' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Nov 14 07:33:32 2015
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class J142tEstadoDepuracionMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.J142tEstadoDepuracionMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(J142tEstadoDepuracionPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(J142tEstadoDepuracionPeer::TABLE_NAME);
		$tMap->setPhpName('J142tEstadoDepuracion');
		$tMap->setClassname('J142tEstadoDepuracion');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('j142t_estado_depuracion_co_estado_depuracion_seq');

		$tMap->addPrimaryKey('CO_ESTADO_DEPURACION', 'CoEstadoDepuracion', 'BIGINT', true, null);

		$tMap->addColumn('TX_ESTADO_DEPURACION', 'TxEstadoDepuracion', 'VARCHAR', true, 255);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'DATE', true, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'DATE', false, null);

	} // doBuild()

} // J142tEstadoDepuracionMapBuilder
