<?php


/**
 * This class adds structure of 'j801t_principio' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Nov 14 07:33:32 2015
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class J801tPrincipioMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.J801tPrincipioMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(J801tPrincipioPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(J801tPrincipioPeer::TABLE_NAME);
		$tMap->setPhpName('J801tPrincipio');
		$tMap->setClassname('J801tPrincipio');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('j801t_principio_co_principio_seq');

		$tMap->addPrimaryKey('CO_PRINCIPIO', 'CoPrincipio', 'BIGINT', true, null);

		$tMap->addColumn('TX_PRINCIPIO', 'TxPrincipio', 'VARCHAR', false, 255);

	} // doBuild()

} // J801tPrincipioMapBuilder
