<?php


/**
 * This class adds structure of 'j808t_producto' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Nov 14 07:33:32 2015
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class J808tProductoMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.J808tProductoMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(J808tProductoPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(J808tProductoPeer::TABLE_NAME);
		$tMap->setPhpName('J808tProducto');
		$tMap->setClassname('J808tProducto');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('j808t_producto_co_producto_seq');

		$tMap->addPrimaryKey('CO_PRODUCTO', 'CoProducto', 'BIGINT', true, null);

		$tMap->addColumn('TX_PRODUCTO', 'TxProducto', 'VARCHAR', false, 255);

		$tMap->addForeignKey('CO_PADRE', 'CoPadre', 'BIGINT', 'j808t_producto', 'CO_PRODUCTO', false, null);

		$tMap->addColumn('TX_HREF', 'TxHref', 'VARCHAR', false, 255);

		$tMap->addColumn('TX_ICONO', 'TxIcono', 'VARCHAR', false, 255);

		$tMap->addColumn('NU_ORDEN', 'NuOrden', 'BIGINT', false, null);

		$tMap->addColumn('TX_SIGLA', 'TxSigla', 'VARCHAR', false, 255);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

		$tMap->addForeignKey('CO_TRANSACCION', 'CoTransaccion', 'BIGINT', 'c801t_transaccion', 'CO_TRANSACCION', false, null);

	} // doBuild()

} // J808tProductoMapBuilder
