<?php


/**
 * This class adds structure of 'j812_persona' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Nov 14 07:33:32 2015
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class J812PersonaMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.J812PersonaMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(J812PersonaPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(J812PersonaPeer::TABLE_NAME);
		$tMap->setPhpName('J812Persona');
		$tMap->setClassname('J812Persona');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('j812_persona_co_persona_seq');

		$tMap->addPrimaryKey('CO_PERSONA', 'CoPersona', 'BIGINT', true, null);

		$tMap->addColumn('NB_PERSONA', 'NbPersona', 'VARCHAR', false, 255);

		$tMap->addColumn('AP_PERSONA', 'ApPersona', 'VARCHAR', false, 255);

		$tMap->addForeignKey('CO_DIVISION', 'CoDivision', 'BIGINT', 'j815t_division', 'CO_DIVISION', true, null);

		$tMap->addForeignKey('CO_ROL', 'CoRol', 'BIGINT', 'j809t_rol', 'CO_ROL', true, null);

		$tMap->addForeignKey('CO_REGION', 'CoRegion', 'BIGINT', 'j813t_region', 'CO_REGION', true, null);

		$tMap->addForeignKey('CO_NEGOCIO', 'CoNegocio', 'BIGINT', 'j814t_negocio', 'CO_NEGOCIO', true, null);

	} // doBuild()

} // J812PersonaMapBuilder
