<?php

/**
 * Base class that represents a row from the 'c804t_seguimiento_accion' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Nov 14 07:33:32 2015
 *
 * @package    lib.model.om
 */
abstract class BaseC804tSeguimientoAccion extends BaseObject  implements Persistent {


  const PEER = 'C804tSeguimientoAccionPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        C804tSeguimientoAccionPeer
	 */
	protected static $peer;

	/**
	 * The value for the co_seguimiento_accion field.
	 * @var        string
	 */
	protected $co_seguimiento_accion;

	/**
	 * The value for the co_accion field.
	 * @var        string
	 */
	protected $co_accion;

	/**
	 * The value for the co_estado_accion field.
	 * @var        string
	 */
	protected $co_estado_accion;

	/**
	 * The value for the co_responsable_sti field.
	 * @var        string
	 */
	protected $co_responsable_sti;

	/**
	 * The value for the co_responsable_ejecutar field.
	 * @var        string
	 */
	protected $co_responsable_ejecutar;

	/**
	 * The value for the co_gerencia_responsable field.
	 * @var        string
	 */
	protected $co_gerencia_responsable;

	/**
	 * The value for the fe_planificada_ejecutar field.
	 * @var        string
	 */
	protected $fe_planificada_ejecutar;

	/**
	 * The value for the fe_seguimiento_sti field.
	 * @var        string
	 */
	protected $fe_seguimiento_sti;

	/**
	 * The value for the tx_respuesta_responsable field.
	 * @var        string
	 */
	protected $tx_respuesta_responsable;

	/**
	 * The value for the tx_observaciones field.
	 * @var        string
	 */
	protected $tx_observaciones;

	/**
	 * The value for the nb_archivo_evidencia field.
	 * @var        string
	 */
	protected $nb_archivo_evidencia;

	/**
	 * The value for the tx_ruta_evidencia field.
	 * @var        string
	 */
	protected $tx_ruta_evidencia;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the co_created_at field.
	 * @var        string
	 */
	protected $co_created_at;

	/**
	 * The value for the co_updated_at field.
	 * @var        string
	 */
	protected $co_updated_at;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseC804tSeguimientoAccion object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [co_seguimiento_accion] column value.
	 * 
	 * @return     string
	 */
	public function getCoSeguimientoAccion()
	{
		return $this->co_seguimiento_accion;
	}

	/**
	 * Get the [co_accion] column value.
	 * 
	 * @return     string
	 */
	public function getCoAccion()
	{
		return $this->co_accion;
	}

	/**
	 * Get the [co_estado_accion] column value.
	 * 
	 * @return     string
	 */
	public function getCoEstadoAccion()
	{
		return $this->co_estado_accion;
	}

	/**
	 * Get the [co_responsable_sti] column value.
	 * 
	 * @return     string
	 */
	public function getCoResponsableSti()
	{
		return $this->co_responsable_sti;
	}

	/**
	 * Get the [co_responsable_ejecutar] column value.
	 * 
	 * @return     string
	 */
	public function getCoResponsableEjecutar()
	{
		return $this->co_responsable_ejecutar;
	}

	/**
	 * Get the [co_gerencia_responsable] column value.
	 * 
	 * @return     string
	 */
	public function getCoGerenciaResponsable()
	{
		return $this->co_gerencia_responsable;
	}

	/**
	 * Get the [optionally formatted] temporal [fe_planificada_ejecutar] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFePlanificadaEjecutar($format = 'Y-m-d')
	{
		if ($this->fe_planificada_ejecutar === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->fe_planificada_ejecutar);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fe_planificada_ejecutar, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [fe_seguimiento_sti] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFeSeguimientoSti($format = 'Y-m-d')
	{
		if ($this->fe_seguimiento_sti === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->fe_seguimiento_sti);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fe_seguimiento_sti, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [tx_respuesta_responsable] column value.
	 * 
	 * @return     string
	 */
	public function getTxRespuestaResponsable()
	{
		return $this->tx_respuesta_responsable;
	}

	/**
	 * Get the [tx_observaciones] column value.
	 * 
	 * @return     string
	 */
	public function getTxObservaciones()
	{
		return $this->tx_observaciones;
	}

	/**
	 * Get the [nb_archivo_evidencia] column value.
	 * 
	 * @return     string
	 */
	public function getNbArchivoEvidencia()
	{
		return $this->nb_archivo_evidencia;
	}

	/**
	 * Get the [tx_ruta_evidencia] column value.
	 * 
	 * @return     string
	 */
	public function getTxRutaEvidencia()
	{
		return $this->tx_ruta_evidencia;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->updated_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [co_created_at] column value.
	 * 
	 * @return     string
	 */
	public function getCoCreatedAt()
	{
		return $this->co_created_at;
	}

	/**
	 * Get the [co_updated_at] column value.
	 * 
	 * @return     string
	 */
	public function getCoUpdatedAt()
	{
		return $this->co_updated_at;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set the value of [co_seguimiento_accion] column.
	 * 
	 * @param      string $v new value
	 * @return     C804tSeguimientoAccion The current object (for fluent API support)
	 */
	public function setCoSeguimientoAccion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_seguimiento_accion !== $v) {
			$this->co_seguimiento_accion = $v;
			$this->modifiedColumns[] = C804tSeguimientoAccionPeer::CO_SEGUIMIENTO_ACCION;
		}

		return $this;
	} // setCoSeguimientoAccion()

	/**
	 * Set the value of [co_accion] column.
	 * 
	 * @param      string $v new value
	 * @return     C804tSeguimientoAccion The current object (for fluent API support)
	 */
	public function setCoAccion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_accion !== $v) {
			$this->co_accion = $v;
			$this->modifiedColumns[] = C804tSeguimientoAccionPeer::CO_ACCION;
		}

		return $this;
	} // setCoAccion()

	/**
	 * Set the value of [co_estado_accion] column.
	 * 
	 * @param      string $v new value
	 * @return     C804tSeguimientoAccion The current object (for fluent API support)
	 */
	public function setCoEstadoAccion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_estado_accion !== $v) {
			$this->co_estado_accion = $v;
			$this->modifiedColumns[] = C804tSeguimientoAccionPeer::CO_ESTADO_ACCION;
		}

		return $this;
	} // setCoEstadoAccion()

	/**
	 * Set the value of [co_responsable_sti] column.
	 * 
	 * @param      string $v new value
	 * @return     C804tSeguimientoAccion The current object (for fluent API support)
	 */
	public function setCoResponsableSti($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_responsable_sti !== $v) {
			$this->co_responsable_sti = $v;
			$this->modifiedColumns[] = C804tSeguimientoAccionPeer::CO_RESPONSABLE_STI;
		}

		return $this;
	} // setCoResponsableSti()

	/**
	 * Set the value of [co_responsable_ejecutar] column.
	 * 
	 * @param      string $v new value
	 * @return     C804tSeguimientoAccion The current object (for fluent API support)
	 */
	public function setCoResponsableEjecutar($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_responsable_ejecutar !== $v) {
			$this->co_responsable_ejecutar = $v;
			$this->modifiedColumns[] = C804tSeguimientoAccionPeer::CO_RESPONSABLE_EJECUTAR;
		}

		return $this;
	} // setCoResponsableEjecutar()

	/**
	 * Set the value of [co_gerencia_responsable] column.
	 * 
	 * @param      string $v new value
	 * @return     C804tSeguimientoAccion The current object (for fluent API support)
	 */
	public function setCoGerenciaResponsable($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_gerencia_responsable !== $v) {
			$this->co_gerencia_responsable = $v;
			$this->modifiedColumns[] = C804tSeguimientoAccionPeer::CO_GERENCIA_RESPONSABLE;
		}

		return $this;
	} // setCoGerenciaResponsable()

	/**
	 * Sets the value of [fe_planificada_ejecutar] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     C804tSeguimientoAccion The current object (for fluent API support)
	 */
	public function setFePlanificadaEjecutar($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fe_planificada_ejecutar !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fe_planificada_ejecutar !== null && $tmpDt = new DateTime($this->fe_planificada_ejecutar)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fe_planificada_ejecutar = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = C804tSeguimientoAccionPeer::FE_PLANIFICADA_EJECUTAR;
			}
		} // if either are not null

		return $this;
	} // setFePlanificadaEjecutar()

	/**
	 * Sets the value of [fe_seguimiento_sti] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     C804tSeguimientoAccion The current object (for fluent API support)
	 */
	public function setFeSeguimientoSti($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fe_seguimiento_sti !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fe_seguimiento_sti !== null && $tmpDt = new DateTime($this->fe_seguimiento_sti)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fe_seguimiento_sti = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = C804tSeguimientoAccionPeer::FE_SEGUIMIENTO_STI;
			}
		} // if either are not null

		return $this;
	} // setFeSeguimientoSti()

	/**
	 * Set the value of [tx_respuesta_responsable] column.
	 * 
	 * @param      string $v new value
	 * @return     C804tSeguimientoAccion The current object (for fluent API support)
	 */
	public function setTxRespuestaResponsable($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_respuesta_responsable !== $v) {
			$this->tx_respuesta_responsable = $v;
			$this->modifiedColumns[] = C804tSeguimientoAccionPeer::TX_RESPUESTA_RESPONSABLE;
		}

		return $this;
	} // setTxRespuestaResponsable()

	/**
	 * Set the value of [tx_observaciones] column.
	 * 
	 * @param      string $v new value
	 * @return     C804tSeguimientoAccion The current object (for fluent API support)
	 */
	public function setTxObservaciones($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_observaciones !== $v) {
			$this->tx_observaciones = $v;
			$this->modifiedColumns[] = C804tSeguimientoAccionPeer::TX_OBSERVACIONES;
		}

		return $this;
	} // setTxObservaciones()

	/**
	 * Set the value of [nb_archivo_evidencia] column.
	 * 
	 * @param      string $v new value
	 * @return     C804tSeguimientoAccion The current object (for fluent API support)
	 */
	public function setNbArchivoEvidencia($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nb_archivo_evidencia !== $v) {
			$this->nb_archivo_evidencia = $v;
			$this->modifiedColumns[] = C804tSeguimientoAccionPeer::NB_ARCHIVO_EVIDENCIA;
		}

		return $this;
	} // setNbArchivoEvidencia()

	/**
	 * Set the value of [tx_ruta_evidencia] column.
	 * 
	 * @param      string $v new value
	 * @return     C804tSeguimientoAccion The current object (for fluent API support)
	 */
	public function setTxRutaEvidencia($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_ruta_evidencia !== $v) {
			$this->tx_ruta_evidencia = $v;
			$this->modifiedColumns[] = C804tSeguimientoAccionPeer::TX_RUTA_EVIDENCIA;
		}

		return $this;
	} // setTxRutaEvidencia()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     C804tSeguimientoAccion The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = C804tSeguimientoAccionPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     C804tSeguimientoAccion The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = C804tSeguimientoAccionPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [co_created_at] column.
	 * 
	 * @param      string $v new value
	 * @return     C804tSeguimientoAccion The current object (for fluent API support)
	 */
	public function setCoCreatedAt($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_created_at !== $v) {
			$this->co_created_at = $v;
			$this->modifiedColumns[] = C804tSeguimientoAccionPeer::CO_CREATED_AT;
		}

		return $this;
	} // setCoCreatedAt()

	/**
	 * Set the value of [co_updated_at] column.
	 * 
	 * @param      string $v new value
	 * @return     C804tSeguimientoAccion The current object (for fluent API support)
	 */
	public function setCoUpdatedAt($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_updated_at !== $v) {
			$this->co_updated_at = $v;
			$this->modifiedColumns[] = C804tSeguimientoAccionPeer::CO_UPDATED_AT;
		}

		return $this;
	} // setCoUpdatedAt()

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     C804tSeguimientoAccion The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = C804tSeguimientoAccionPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->co_seguimiento_accion = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->co_accion = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->co_estado_accion = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->co_responsable_sti = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->co_responsable_ejecutar = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->co_gerencia_responsable = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->fe_planificada_ejecutar = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->fe_seguimiento_sti = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->tx_respuesta_responsable = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->tx_observaciones = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->nb_archivo_evidencia = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->tx_ruta_evidencia = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->created_at = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->updated_at = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->co_created_at = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->co_updated_at = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->id = ($row[$startcol + 16] !== null) ? (int) $row[$startcol + 16] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 17; // 17 = C804tSeguimientoAccionPeer::NUM_COLUMNS - C804tSeguimientoAccionPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating C804tSeguimientoAccion object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(C804tSeguimientoAccionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = C804tSeguimientoAccionPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseC804tSeguimientoAccion:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(C804tSeguimientoAccionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			C804tSeguimientoAccionPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseC804tSeguimientoAccion:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseC804tSeguimientoAccion:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(C804tSeguimientoAccionPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(C804tSeguimientoAccionPeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(C804tSeguimientoAccionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseC804tSeguimientoAccion:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			C804tSeguimientoAccionPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = C804tSeguimientoAccionPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = C804tSeguimientoAccionPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += C804tSeguimientoAccionPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = C804tSeguimientoAccionPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = C804tSeguimientoAccionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getCoSeguimientoAccion();
				break;
			case 1:
				return $this->getCoAccion();
				break;
			case 2:
				return $this->getCoEstadoAccion();
				break;
			case 3:
				return $this->getCoResponsableSti();
				break;
			case 4:
				return $this->getCoResponsableEjecutar();
				break;
			case 5:
				return $this->getCoGerenciaResponsable();
				break;
			case 6:
				return $this->getFePlanificadaEjecutar();
				break;
			case 7:
				return $this->getFeSeguimientoSti();
				break;
			case 8:
				return $this->getTxRespuestaResponsable();
				break;
			case 9:
				return $this->getTxObservaciones();
				break;
			case 10:
				return $this->getNbArchivoEvidencia();
				break;
			case 11:
				return $this->getTxRutaEvidencia();
				break;
			case 12:
				return $this->getCreatedAt();
				break;
			case 13:
				return $this->getUpdatedAt();
				break;
			case 14:
				return $this->getCoCreatedAt();
				break;
			case 15:
				return $this->getCoUpdatedAt();
				break;
			case 16:
				return $this->getId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = C804tSeguimientoAccionPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getCoSeguimientoAccion(),
			$keys[1] => $this->getCoAccion(),
			$keys[2] => $this->getCoEstadoAccion(),
			$keys[3] => $this->getCoResponsableSti(),
			$keys[4] => $this->getCoResponsableEjecutar(),
			$keys[5] => $this->getCoGerenciaResponsable(),
			$keys[6] => $this->getFePlanificadaEjecutar(),
			$keys[7] => $this->getFeSeguimientoSti(),
			$keys[8] => $this->getTxRespuestaResponsable(),
			$keys[9] => $this->getTxObservaciones(),
			$keys[10] => $this->getNbArchivoEvidencia(),
			$keys[11] => $this->getTxRutaEvidencia(),
			$keys[12] => $this->getCreatedAt(),
			$keys[13] => $this->getUpdatedAt(),
			$keys[14] => $this->getCoCreatedAt(),
			$keys[15] => $this->getCoUpdatedAt(),
			$keys[16] => $this->getId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = C804tSeguimientoAccionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setCoSeguimientoAccion($value);
				break;
			case 1:
				$this->setCoAccion($value);
				break;
			case 2:
				$this->setCoEstadoAccion($value);
				break;
			case 3:
				$this->setCoResponsableSti($value);
				break;
			case 4:
				$this->setCoResponsableEjecutar($value);
				break;
			case 5:
				$this->setCoGerenciaResponsable($value);
				break;
			case 6:
				$this->setFePlanificadaEjecutar($value);
				break;
			case 7:
				$this->setFeSeguimientoSti($value);
				break;
			case 8:
				$this->setTxRespuestaResponsable($value);
				break;
			case 9:
				$this->setTxObservaciones($value);
				break;
			case 10:
				$this->setNbArchivoEvidencia($value);
				break;
			case 11:
				$this->setTxRutaEvidencia($value);
				break;
			case 12:
				$this->setCreatedAt($value);
				break;
			case 13:
				$this->setUpdatedAt($value);
				break;
			case 14:
				$this->setCoCreatedAt($value);
				break;
			case 15:
				$this->setCoUpdatedAt($value);
				break;
			case 16:
				$this->setId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = C804tSeguimientoAccionPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setCoSeguimientoAccion($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCoAccion($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCoEstadoAccion($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCoResponsableSti($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setCoResponsableEjecutar($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setCoGerenciaResponsable($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setFePlanificadaEjecutar($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setFeSeguimientoSti($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setTxRespuestaResponsable($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setTxObservaciones($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setNbArchivoEvidencia($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setTxRutaEvidencia($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setCreatedAt($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setUpdatedAt($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setCoCreatedAt($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setCoUpdatedAt($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setId($arr[$keys[16]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(C804tSeguimientoAccionPeer::DATABASE_NAME);

		if ($this->isColumnModified(C804tSeguimientoAccionPeer::CO_SEGUIMIENTO_ACCION)) $criteria->add(C804tSeguimientoAccionPeer::CO_SEGUIMIENTO_ACCION, $this->co_seguimiento_accion);
		if ($this->isColumnModified(C804tSeguimientoAccionPeer::CO_ACCION)) $criteria->add(C804tSeguimientoAccionPeer::CO_ACCION, $this->co_accion);
		if ($this->isColumnModified(C804tSeguimientoAccionPeer::CO_ESTADO_ACCION)) $criteria->add(C804tSeguimientoAccionPeer::CO_ESTADO_ACCION, $this->co_estado_accion);
		if ($this->isColumnModified(C804tSeguimientoAccionPeer::CO_RESPONSABLE_STI)) $criteria->add(C804tSeguimientoAccionPeer::CO_RESPONSABLE_STI, $this->co_responsable_sti);
		if ($this->isColumnModified(C804tSeguimientoAccionPeer::CO_RESPONSABLE_EJECUTAR)) $criteria->add(C804tSeguimientoAccionPeer::CO_RESPONSABLE_EJECUTAR, $this->co_responsable_ejecutar);
		if ($this->isColumnModified(C804tSeguimientoAccionPeer::CO_GERENCIA_RESPONSABLE)) $criteria->add(C804tSeguimientoAccionPeer::CO_GERENCIA_RESPONSABLE, $this->co_gerencia_responsable);
		if ($this->isColumnModified(C804tSeguimientoAccionPeer::FE_PLANIFICADA_EJECUTAR)) $criteria->add(C804tSeguimientoAccionPeer::FE_PLANIFICADA_EJECUTAR, $this->fe_planificada_ejecutar);
		if ($this->isColumnModified(C804tSeguimientoAccionPeer::FE_SEGUIMIENTO_STI)) $criteria->add(C804tSeguimientoAccionPeer::FE_SEGUIMIENTO_STI, $this->fe_seguimiento_sti);
		if ($this->isColumnModified(C804tSeguimientoAccionPeer::TX_RESPUESTA_RESPONSABLE)) $criteria->add(C804tSeguimientoAccionPeer::TX_RESPUESTA_RESPONSABLE, $this->tx_respuesta_responsable);
		if ($this->isColumnModified(C804tSeguimientoAccionPeer::TX_OBSERVACIONES)) $criteria->add(C804tSeguimientoAccionPeer::TX_OBSERVACIONES, $this->tx_observaciones);
		if ($this->isColumnModified(C804tSeguimientoAccionPeer::NB_ARCHIVO_EVIDENCIA)) $criteria->add(C804tSeguimientoAccionPeer::NB_ARCHIVO_EVIDENCIA, $this->nb_archivo_evidencia);
		if ($this->isColumnModified(C804tSeguimientoAccionPeer::TX_RUTA_EVIDENCIA)) $criteria->add(C804tSeguimientoAccionPeer::TX_RUTA_EVIDENCIA, $this->tx_ruta_evidencia);
		if ($this->isColumnModified(C804tSeguimientoAccionPeer::CREATED_AT)) $criteria->add(C804tSeguimientoAccionPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(C804tSeguimientoAccionPeer::UPDATED_AT)) $criteria->add(C804tSeguimientoAccionPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(C804tSeguimientoAccionPeer::CO_CREATED_AT)) $criteria->add(C804tSeguimientoAccionPeer::CO_CREATED_AT, $this->co_created_at);
		if ($this->isColumnModified(C804tSeguimientoAccionPeer::CO_UPDATED_AT)) $criteria->add(C804tSeguimientoAccionPeer::CO_UPDATED_AT, $this->co_updated_at);
		if ($this->isColumnModified(C804tSeguimientoAccionPeer::ID)) $criteria->add(C804tSeguimientoAccionPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(C804tSeguimientoAccionPeer::DATABASE_NAME);

		$criteria->add(C804tSeguimientoAccionPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of C804tSeguimientoAccion (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCoAccion($this->co_accion);

		$copyObj->setCoEstadoAccion($this->co_estado_accion);

		$copyObj->setCoResponsableSti($this->co_responsable_sti);

		$copyObj->setCoResponsableEjecutar($this->co_responsable_ejecutar);

		$copyObj->setCoGerenciaResponsable($this->co_gerencia_responsable);

		$copyObj->setFePlanificadaEjecutar($this->fe_planificada_ejecutar);

		$copyObj->setFeSeguimientoSti($this->fe_seguimiento_sti);

		$copyObj->setTxRespuestaResponsable($this->tx_respuesta_responsable);

		$copyObj->setTxObservaciones($this->tx_observaciones);

		$copyObj->setNbArchivoEvidencia($this->nb_archivo_evidencia);

		$copyObj->setTxRutaEvidencia($this->tx_ruta_evidencia);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setCoCreatedAt($this->co_created_at);

		$copyObj->setCoUpdatedAt($this->co_updated_at);


		$copyObj->setNew(true);

		$copyObj->setCoSeguimientoAccion(NULL); // this is a auto-increment column, so set to default value

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     C804tSeguimientoAccion Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     C804tSeguimientoAccionPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new C804tSeguimientoAccionPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseC804tSeguimientoAccion:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseC804tSeguimientoAccion::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseC804tSeguimientoAccion
