<?php

/**
 * Base class that represents a row from the 'c008t_anexos_forense' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Nov 14 07:33:32 2015
 *
 * @package    lib.model.om
 */
abstract class BaseC008tAnexosForense extends BaseObject  implements Persistent {


  const PEER = 'C008tAnexosForensePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        C008tAnexosForensePeer
	 */
	protected static $peer;

	/**
	 * The value for the co_anexos_forense field.
	 * @var        string
	 */
	protected $co_anexos_forense;

	/**
	 * The value for the co_informe_forense field.
	 * @var        string
	 */
	protected $co_informe_forense;

	/**
	 * The value for the tx_titulo field.
	 * @var        string
	 */
	protected $tx_titulo;

	/**
	 * The value for the tx_descripcion field.
	 * @var        string
	 */
	protected $tx_descripcion;

	/**
	 * The value for the tx_ruta field.
	 * @var        string
	 */
	protected $tx_ruta;

	/**
	 * The value for the nb_archivo field.
	 * @var        string
	 */
	protected $nb_archivo;

	/**
	 * The value for the co_clasificacion field.
	 * @var        string
	 */
	protected $co_clasificacion;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        C002tInformeForense
	 */
	protected $aC002tInformeForense;

	/**
	 * @var        J802tClasificacion
	 */
	protected $aJ802tClasificacion;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseC008tAnexosForense object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [co_anexos_forense] column value.
	 * 
	 * @return     string
	 */
	public function getCoAnexosForense()
	{
		return $this->co_anexos_forense;
	}

	/**
	 * Get the [co_informe_forense] column value.
	 * 
	 * @return     string
	 */
	public function getCoInformeForense()
	{
		return $this->co_informe_forense;
	}

	/**
	 * Get the [tx_titulo] column value.
	 * 
	 * @return     string
	 */
	public function getTxTitulo()
	{
		return $this->tx_titulo;
	}

	/**
	 * Get the [tx_descripcion] column value.
	 * 
	 * @return     string
	 */
	public function getTxDescripcion()
	{
		return $this->tx_descripcion;
	}

	/**
	 * Get the [tx_ruta] column value.
	 * 
	 * @return     string
	 */
	public function getTxRuta()
	{
		return $this->tx_ruta;
	}

	/**
	 * Get the [nb_archivo] column value.
	 * 
	 * @return     string
	 */
	public function getNbArchivo()
	{
		return $this->nb_archivo;
	}

	/**
	 * Get the [co_clasificacion] column value.
	 * 
	 * @return     string
	 */
	public function getCoClasificacion()
	{
		return $this->co_clasificacion;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->updated_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [co_anexos_forense] column.
	 * 
	 * @param      string $v new value
	 * @return     C008tAnexosForense The current object (for fluent API support)
	 */
	public function setCoAnexosForense($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_anexos_forense !== $v) {
			$this->co_anexos_forense = $v;
			$this->modifiedColumns[] = C008tAnexosForensePeer::CO_ANEXOS_FORENSE;
		}

		return $this;
	} // setCoAnexosForense()

	/**
	 * Set the value of [co_informe_forense] column.
	 * 
	 * @param      string $v new value
	 * @return     C008tAnexosForense The current object (for fluent API support)
	 */
	public function setCoInformeForense($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_informe_forense !== $v) {
			$this->co_informe_forense = $v;
			$this->modifiedColumns[] = C008tAnexosForensePeer::CO_INFORME_FORENSE;
		}

		if ($this->aC002tInformeForense !== null && $this->aC002tInformeForense->getCoInformeForense() !== $v) {
			$this->aC002tInformeForense = null;
		}

		return $this;
	} // setCoInformeForense()

	/**
	 * Set the value of [tx_titulo] column.
	 * 
	 * @param      string $v new value
	 * @return     C008tAnexosForense The current object (for fluent API support)
	 */
	public function setTxTitulo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_titulo !== $v) {
			$this->tx_titulo = $v;
			$this->modifiedColumns[] = C008tAnexosForensePeer::TX_TITULO;
		}

		return $this;
	} // setTxTitulo()

	/**
	 * Set the value of [tx_descripcion] column.
	 * 
	 * @param      string $v new value
	 * @return     C008tAnexosForense The current object (for fluent API support)
	 */
	public function setTxDescripcion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_descripcion !== $v) {
			$this->tx_descripcion = $v;
			$this->modifiedColumns[] = C008tAnexosForensePeer::TX_DESCRIPCION;
		}

		return $this;
	} // setTxDescripcion()

	/**
	 * Set the value of [tx_ruta] column.
	 * 
	 * @param      string $v new value
	 * @return     C008tAnexosForense The current object (for fluent API support)
	 */
	public function setTxRuta($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_ruta !== $v) {
			$this->tx_ruta = $v;
			$this->modifiedColumns[] = C008tAnexosForensePeer::TX_RUTA;
		}

		return $this;
	} // setTxRuta()

	/**
	 * Set the value of [nb_archivo] column.
	 * 
	 * @param      string $v new value
	 * @return     C008tAnexosForense The current object (for fluent API support)
	 */
	public function setNbArchivo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nb_archivo !== $v) {
			$this->nb_archivo = $v;
			$this->modifiedColumns[] = C008tAnexosForensePeer::NB_ARCHIVO;
		}

		return $this;
	} // setNbArchivo()

	/**
	 * Set the value of [co_clasificacion] column.
	 * 
	 * @param      string $v new value
	 * @return     C008tAnexosForense The current object (for fluent API support)
	 */
	public function setCoClasificacion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_clasificacion !== $v) {
			$this->co_clasificacion = $v;
			$this->modifiedColumns[] = C008tAnexosForensePeer::CO_CLASIFICACION;
		}

		if ($this->aJ802tClasificacion !== null && $this->aJ802tClasificacion->getCoClasificacion() !== $v) {
			$this->aJ802tClasificacion = null;
		}

		return $this;
	} // setCoClasificacion()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     C008tAnexosForense The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = C008tAnexosForensePeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     C008tAnexosForense The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = C008tAnexosForensePeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->co_anexos_forense = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->co_informe_forense = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->tx_titulo = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->tx_descripcion = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->tx_ruta = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->nb_archivo = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->co_clasificacion = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->created_at = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->updated_at = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 9; // 9 = C008tAnexosForensePeer::NUM_COLUMNS - C008tAnexosForensePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating C008tAnexosForense object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aC002tInformeForense !== null && $this->co_informe_forense !== $this->aC002tInformeForense->getCoInformeForense()) {
			$this->aC002tInformeForense = null;
		}
		if ($this->aJ802tClasificacion !== null && $this->co_clasificacion !== $this->aJ802tClasificacion->getCoClasificacion()) {
			$this->aJ802tClasificacion = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(C008tAnexosForensePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = C008tAnexosForensePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aC002tInformeForense = null;
			$this->aJ802tClasificacion = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseC008tAnexosForense:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(C008tAnexosForensePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			C008tAnexosForensePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseC008tAnexosForense:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseC008tAnexosForense:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(C008tAnexosForensePeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(C008tAnexosForensePeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(C008tAnexosForensePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseC008tAnexosForense:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			C008tAnexosForensePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aC002tInformeForense !== null) {
				if ($this->aC002tInformeForense->isModified() || $this->aC002tInformeForense->isNew()) {
					$affectedRows += $this->aC002tInformeForense->save($con);
				}
				$this->setC002tInformeForense($this->aC002tInformeForense);
			}

			if ($this->aJ802tClasificacion !== null) {
				if ($this->aJ802tClasificacion->isModified() || $this->aJ802tClasificacion->isNew()) {
					$affectedRows += $this->aJ802tClasificacion->save($con);
				}
				$this->setJ802tClasificacion($this->aJ802tClasificacion);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = C008tAnexosForensePeer::CO_ANEXOS_FORENSE;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = C008tAnexosForensePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setCoAnexosForense($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += C008tAnexosForensePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aC002tInformeForense !== null) {
				if (!$this->aC002tInformeForense->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aC002tInformeForense->getValidationFailures());
				}
			}

			if ($this->aJ802tClasificacion !== null) {
				if (!$this->aJ802tClasificacion->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJ802tClasificacion->getValidationFailures());
				}
			}


			if (($retval = C008tAnexosForensePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = C008tAnexosForensePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getCoAnexosForense();
				break;
			case 1:
				return $this->getCoInformeForense();
				break;
			case 2:
				return $this->getTxTitulo();
				break;
			case 3:
				return $this->getTxDescripcion();
				break;
			case 4:
				return $this->getTxRuta();
				break;
			case 5:
				return $this->getNbArchivo();
				break;
			case 6:
				return $this->getCoClasificacion();
				break;
			case 7:
				return $this->getCreatedAt();
				break;
			case 8:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = C008tAnexosForensePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getCoAnexosForense(),
			$keys[1] => $this->getCoInformeForense(),
			$keys[2] => $this->getTxTitulo(),
			$keys[3] => $this->getTxDescripcion(),
			$keys[4] => $this->getTxRuta(),
			$keys[5] => $this->getNbArchivo(),
			$keys[6] => $this->getCoClasificacion(),
			$keys[7] => $this->getCreatedAt(),
			$keys[8] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = C008tAnexosForensePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setCoAnexosForense($value);
				break;
			case 1:
				$this->setCoInformeForense($value);
				break;
			case 2:
				$this->setTxTitulo($value);
				break;
			case 3:
				$this->setTxDescripcion($value);
				break;
			case 4:
				$this->setTxRuta($value);
				break;
			case 5:
				$this->setNbArchivo($value);
				break;
			case 6:
				$this->setCoClasificacion($value);
				break;
			case 7:
				$this->setCreatedAt($value);
				break;
			case 8:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = C008tAnexosForensePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setCoAnexosForense($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCoInformeForense($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTxTitulo($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTxDescripcion($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setTxRuta($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setNbArchivo($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCoClasificacion($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCreatedAt($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setUpdatedAt($arr[$keys[8]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(C008tAnexosForensePeer::DATABASE_NAME);

		if ($this->isColumnModified(C008tAnexosForensePeer::CO_ANEXOS_FORENSE)) $criteria->add(C008tAnexosForensePeer::CO_ANEXOS_FORENSE, $this->co_anexos_forense);
		if ($this->isColumnModified(C008tAnexosForensePeer::CO_INFORME_FORENSE)) $criteria->add(C008tAnexosForensePeer::CO_INFORME_FORENSE, $this->co_informe_forense);
		if ($this->isColumnModified(C008tAnexosForensePeer::TX_TITULO)) $criteria->add(C008tAnexosForensePeer::TX_TITULO, $this->tx_titulo);
		if ($this->isColumnModified(C008tAnexosForensePeer::TX_DESCRIPCION)) $criteria->add(C008tAnexosForensePeer::TX_DESCRIPCION, $this->tx_descripcion);
		if ($this->isColumnModified(C008tAnexosForensePeer::TX_RUTA)) $criteria->add(C008tAnexosForensePeer::TX_RUTA, $this->tx_ruta);
		if ($this->isColumnModified(C008tAnexosForensePeer::NB_ARCHIVO)) $criteria->add(C008tAnexosForensePeer::NB_ARCHIVO, $this->nb_archivo);
		if ($this->isColumnModified(C008tAnexosForensePeer::CO_CLASIFICACION)) $criteria->add(C008tAnexosForensePeer::CO_CLASIFICACION, $this->co_clasificacion);
		if ($this->isColumnModified(C008tAnexosForensePeer::CREATED_AT)) $criteria->add(C008tAnexosForensePeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(C008tAnexosForensePeer::UPDATED_AT)) $criteria->add(C008tAnexosForensePeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(C008tAnexosForensePeer::DATABASE_NAME);

		$criteria->add(C008tAnexosForensePeer::CO_ANEXOS_FORENSE, $this->co_anexos_forense);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getCoAnexosForense();
	}

	/**
	 * Generic method to set the primary key (co_anexos_forense column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setCoAnexosForense($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of C008tAnexosForense (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCoInformeForense($this->co_informe_forense);

		$copyObj->setTxTitulo($this->tx_titulo);

		$copyObj->setTxDescripcion($this->tx_descripcion);

		$copyObj->setTxRuta($this->tx_ruta);

		$copyObj->setNbArchivo($this->nb_archivo);

		$copyObj->setCoClasificacion($this->co_clasificacion);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		$copyObj->setNew(true);

		$copyObj->setCoAnexosForense(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     C008tAnexosForense Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     C008tAnexosForensePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new C008tAnexosForensePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a C002tInformeForense object.
	 *
	 * @param      C002tInformeForense $v
	 * @return     C008tAnexosForense The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setC002tInformeForense(C002tInformeForense $v = null)
	{
		if ($v === null) {
			$this->setCoInformeForense(NULL);
		} else {
			$this->setCoInformeForense($v->getCoInformeForense());
		}

		$this->aC002tInformeForense = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the C002tInformeForense object, it will not be re-added.
		if ($v !== null) {
			$v->addC008tAnexosForense($this);
		}

		return $this;
	}


	/**
	 * Get the associated C002tInformeForense object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     C002tInformeForense The associated C002tInformeForense object.
	 * @throws     PropelException
	 */
	public function getC002tInformeForense(PropelPDO $con = null)
	{
		if ($this->aC002tInformeForense === null && (($this->co_informe_forense !== "" && $this->co_informe_forense !== null))) {
			$c = new Criteria(C002tInformeForensePeer::DATABASE_NAME);
			$c->add(C002tInformeForensePeer::CO_INFORME_FORENSE, $this->co_informe_forense);
			$this->aC002tInformeForense = C002tInformeForensePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aC002tInformeForense->addC008tAnexosForenses($this);
			 */
		}
		return $this->aC002tInformeForense;
	}

	/**
	 * Declares an association between this object and a J802tClasificacion object.
	 *
	 * @param      J802tClasificacion $v
	 * @return     C008tAnexosForense The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJ802tClasificacion(J802tClasificacion $v = null)
	{
		if ($v === null) {
			$this->setCoClasificacion(NULL);
		} else {
			$this->setCoClasificacion($v->getCoClasificacion());
		}

		$this->aJ802tClasificacion = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the J802tClasificacion object, it will not be re-added.
		if ($v !== null) {
			$v->addC008tAnexosForense($this);
		}

		return $this;
	}


	/**
	 * Get the associated J802tClasificacion object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     J802tClasificacion The associated J802tClasificacion object.
	 * @throws     PropelException
	 */
	public function getJ802tClasificacion(PropelPDO $con = null)
	{
		if ($this->aJ802tClasificacion === null && (($this->co_clasificacion !== "" && $this->co_clasificacion !== null))) {
			$c = new Criteria(J802tClasificacionPeer::DATABASE_NAME);
			$c->add(J802tClasificacionPeer::CO_CLASIFICACION, $this->co_clasificacion);
			$this->aJ802tClasificacion = J802tClasificacionPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJ802tClasificacion->addC008tAnexosForenses($this);
			 */
		}
		return $this->aJ802tClasificacion;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aC002tInformeForense = null;
			$this->aJ802tClasificacion = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseC008tAnexosForense:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseC008tAnexosForense::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseC008tAnexosForense
