<?php

/**
 * Base class that represents a row from the 'j822t_nivel_riesgo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Nov 14 07:33:32 2015
 *
 * @package    lib.model.om
 */
abstract class BaseJ822tNivelRiesgo extends BaseObject  implements Persistent {


  const PEER = 'J822tNivelRiesgoPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        J822tNivelRiesgoPeer
	 */
	protected static $peer;

	/**
	 * The value for the co_nivel_riesgo field.
	 * @var        string
	 */
	protected $co_nivel_riesgo;

	/**
	 * The value for the tx_nivel_riesgo field.
	 * @var        string
	 */
	protected $tx_nivel_riesgo;

	/**
	 * The value for the nu_valor field.
	 * @var        string
	 */
	protected $nu_valor;

	/**
	 * The value for the tx_descripcion field.
	 * @var        string
	 */
	protected $tx_descripcion;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the co_created_at field.
	 * @var        string
	 */
	protected $co_created_at;

	/**
	 * The value for the co_updated_at field.
	 * @var        string
	 */
	protected $co_updated_at;

	/**
	 * @var        array J825tMatrizRiesgo[] Collection to store aggregation of J825tMatrizRiesgo objects.
	 */
	protected $collJ825tMatrizRiesgos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collJ825tMatrizRiesgos.
	 */
	private $lastJ825tMatrizRiesgoCriteria = null;

	/**
	 * @var        array J827tTipoRiesgo[] Collection to store aggregation of J827tTipoRiesgo objects.
	 */
	protected $collJ827tTipoRiesgos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collJ827tTipoRiesgos.
	 */
	private $lastJ827tTipoRiesgoCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseJ822tNivelRiesgo object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [co_nivel_riesgo] column value.
	 * 
	 * @return     string
	 */
	public function getCoNivelRiesgo()
	{
		return $this->co_nivel_riesgo;
	}

	/**
	 * Get the [tx_nivel_riesgo] column value.
	 * 
	 * @return     string
	 */
	public function getTxNivelRiesgo()
	{
		return $this->tx_nivel_riesgo;
	}

	/**
	 * Get the [nu_valor] column value.
	 * 
	 * @return     string
	 */
	public function getNuValor()
	{
		return $this->nu_valor;
	}

	/**
	 * Get the [tx_descripcion] column value.
	 * 
	 * @return     string
	 */
	public function getTxDescripcion()
	{
		return $this->tx_descripcion;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->updated_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [co_created_at] column value.
	 * 
	 * @return     string
	 */
	public function getCoCreatedAt()
	{
		return $this->co_created_at;
	}

	/**
	 * Get the [co_updated_at] column value.
	 * 
	 * @return     string
	 */
	public function getCoUpdatedAt()
	{
		return $this->co_updated_at;
	}

	/**
	 * Set the value of [co_nivel_riesgo] column.
	 * 
	 * @param      string $v new value
	 * @return     J822tNivelRiesgo The current object (for fluent API support)
	 */
	public function setCoNivelRiesgo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_nivel_riesgo !== $v) {
			$this->co_nivel_riesgo = $v;
			$this->modifiedColumns[] = J822tNivelRiesgoPeer::CO_NIVEL_RIESGO;
		}

		return $this;
	} // setCoNivelRiesgo()

	/**
	 * Set the value of [tx_nivel_riesgo] column.
	 * 
	 * @param      string $v new value
	 * @return     J822tNivelRiesgo The current object (for fluent API support)
	 */
	public function setTxNivelRiesgo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_nivel_riesgo !== $v) {
			$this->tx_nivel_riesgo = $v;
			$this->modifiedColumns[] = J822tNivelRiesgoPeer::TX_NIVEL_RIESGO;
		}

		return $this;
	} // setTxNivelRiesgo()

	/**
	 * Set the value of [nu_valor] column.
	 * 
	 * @param      string $v new value
	 * @return     J822tNivelRiesgo The current object (for fluent API support)
	 */
	public function setNuValor($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nu_valor !== $v) {
			$this->nu_valor = $v;
			$this->modifiedColumns[] = J822tNivelRiesgoPeer::NU_VALOR;
		}

		return $this;
	} // setNuValor()

	/**
	 * Set the value of [tx_descripcion] column.
	 * 
	 * @param      string $v new value
	 * @return     J822tNivelRiesgo The current object (for fluent API support)
	 */
	public function setTxDescripcion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_descripcion !== $v) {
			$this->tx_descripcion = $v;
			$this->modifiedColumns[] = J822tNivelRiesgoPeer::TX_DESCRIPCION;
		}

		return $this;
	} // setTxDescripcion()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     J822tNivelRiesgo The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = J822tNivelRiesgoPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     J822tNivelRiesgo The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = J822tNivelRiesgoPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [co_created_at] column.
	 * 
	 * @param      string $v new value
	 * @return     J822tNivelRiesgo The current object (for fluent API support)
	 */
	public function setCoCreatedAt($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_created_at !== $v) {
			$this->co_created_at = $v;
			$this->modifiedColumns[] = J822tNivelRiesgoPeer::CO_CREATED_AT;
		}

		return $this;
	} // setCoCreatedAt()

	/**
	 * Set the value of [co_updated_at] column.
	 * 
	 * @param      string $v new value
	 * @return     J822tNivelRiesgo The current object (for fluent API support)
	 */
	public function setCoUpdatedAt($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_updated_at !== $v) {
			$this->co_updated_at = $v;
			$this->modifiedColumns[] = J822tNivelRiesgoPeer::CO_UPDATED_AT;
		}

		return $this;
	} // setCoUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->co_nivel_riesgo = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->tx_nivel_riesgo = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->nu_valor = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->tx_descripcion = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->created_at = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->updated_at = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->co_created_at = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->co_updated_at = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 8; // 8 = J822tNivelRiesgoPeer::NUM_COLUMNS - J822tNivelRiesgoPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating J822tNivelRiesgo object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(J822tNivelRiesgoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = J822tNivelRiesgoPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collJ825tMatrizRiesgos = null;
			$this->lastJ825tMatrizRiesgoCriteria = null;

			$this->collJ827tTipoRiesgos = null;
			$this->lastJ827tTipoRiesgoCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseJ822tNivelRiesgo:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(J822tNivelRiesgoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			J822tNivelRiesgoPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseJ822tNivelRiesgo:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseJ822tNivelRiesgo:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(J822tNivelRiesgoPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(J822tNivelRiesgoPeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(J822tNivelRiesgoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseJ822tNivelRiesgo:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			J822tNivelRiesgoPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = J822tNivelRiesgoPeer::CO_NIVEL_RIESGO;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = J822tNivelRiesgoPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setCoNivelRiesgo($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += J822tNivelRiesgoPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collJ825tMatrizRiesgos !== null) {
				foreach ($this->collJ825tMatrizRiesgos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collJ827tTipoRiesgos !== null) {
				foreach ($this->collJ827tTipoRiesgos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = J822tNivelRiesgoPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collJ825tMatrizRiesgos !== null) {
					foreach ($this->collJ825tMatrizRiesgos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collJ827tTipoRiesgos !== null) {
					foreach ($this->collJ827tTipoRiesgos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = J822tNivelRiesgoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getCoNivelRiesgo();
				break;
			case 1:
				return $this->getTxNivelRiesgo();
				break;
			case 2:
				return $this->getNuValor();
				break;
			case 3:
				return $this->getTxDescripcion();
				break;
			case 4:
				return $this->getCreatedAt();
				break;
			case 5:
				return $this->getUpdatedAt();
				break;
			case 6:
				return $this->getCoCreatedAt();
				break;
			case 7:
				return $this->getCoUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = J822tNivelRiesgoPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getCoNivelRiesgo(),
			$keys[1] => $this->getTxNivelRiesgo(),
			$keys[2] => $this->getNuValor(),
			$keys[3] => $this->getTxDescripcion(),
			$keys[4] => $this->getCreatedAt(),
			$keys[5] => $this->getUpdatedAt(),
			$keys[6] => $this->getCoCreatedAt(),
			$keys[7] => $this->getCoUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = J822tNivelRiesgoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setCoNivelRiesgo($value);
				break;
			case 1:
				$this->setTxNivelRiesgo($value);
				break;
			case 2:
				$this->setNuValor($value);
				break;
			case 3:
				$this->setTxDescripcion($value);
				break;
			case 4:
				$this->setCreatedAt($value);
				break;
			case 5:
				$this->setUpdatedAt($value);
				break;
			case 6:
				$this->setCoCreatedAt($value);
				break;
			case 7:
				$this->setCoUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = J822tNivelRiesgoPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setCoNivelRiesgo($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setTxNivelRiesgo($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setNuValor($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTxDescripcion($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setCreatedAt($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setUpdatedAt($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCoCreatedAt($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCoUpdatedAt($arr[$keys[7]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(J822tNivelRiesgoPeer::DATABASE_NAME);

		if ($this->isColumnModified(J822tNivelRiesgoPeer::CO_NIVEL_RIESGO)) $criteria->add(J822tNivelRiesgoPeer::CO_NIVEL_RIESGO, $this->co_nivel_riesgo);
		if ($this->isColumnModified(J822tNivelRiesgoPeer::TX_NIVEL_RIESGO)) $criteria->add(J822tNivelRiesgoPeer::TX_NIVEL_RIESGO, $this->tx_nivel_riesgo);
		if ($this->isColumnModified(J822tNivelRiesgoPeer::NU_VALOR)) $criteria->add(J822tNivelRiesgoPeer::NU_VALOR, $this->nu_valor);
		if ($this->isColumnModified(J822tNivelRiesgoPeer::TX_DESCRIPCION)) $criteria->add(J822tNivelRiesgoPeer::TX_DESCRIPCION, $this->tx_descripcion);
		if ($this->isColumnModified(J822tNivelRiesgoPeer::CREATED_AT)) $criteria->add(J822tNivelRiesgoPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(J822tNivelRiesgoPeer::UPDATED_AT)) $criteria->add(J822tNivelRiesgoPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(J822tNivelRiesgoPeer::CO_CREATED_AT)) $criteria->add(J822tNivelRiesgoPeer::CO_CREATED_AT, $this->co_created_at);
		if ($this->isColumnModified(J822tNivelRiesgoPeer::CO_UPDATED_AT)) $criteria->add(J822tNivelRiesgoPeer::CO_UPDATED_AT, $this->co_updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(J822tNivelRiesgoPeer::DATABASE_NAME);

		$criteria->add(J822tNivelRiesgoPeer::CO_NIVEL_RIESGO, $this->co_nivel_riesgo);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getCoNivelRiesgo();
	}

	/**
	 * Generic method to set the primary key (co_nivel_riesgo column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setCoNivelRiesgo($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of J822tNivelRiesgo (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setTxNivelRiesgo($this->tx_nivel_riesgo);

		$copyObj->setNuValor($this->nu_valor);

		$copyObj->setTxDescripcion($this->tx_descripcion);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setCoCreatedAt($this->co_created_at);

		$copyObj->setCoUpdatedAt($this->co_updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getJ825tMatrizRiesgos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addJ825tMatrizRiesgo($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getJ827tTipoRiesgos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addJ827tTipoRiesgo($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setCoNivelRiesgo(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     J822tNivelRiesgo Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     J822tNivelRiesgoPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new J822tNivelRiesgoPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collJ825tMatrizRiesgos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addJ825tMatrizRiesgos()
	 */
	public function clearJ825tMatrizRiesgos()
	{
		$this->collJ825tMatrizRiesgos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collJ825tMatrizRiesgos collection (array).
	 *
	 * By default this just sets the collJ825tMatrizRiesgos collection to an empty array (like clearcollJ825tMatrizRiesgos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initJ825tMatrizRiesgos()
	{
		$this->collJ825tMatrizRiesgos = array();
	}

	/**
	 * Gets an array of J825tMatrizRiesgo objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this J822tNivelRiesgo has previously been saved, it will retrieve
	 * related J825tMatrizRiesgos from storage. If this J822tNivelRiesgo is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array J825tMatrizRiesgo[]
	 * @throws     PropelException
	 */
	public function getJ825tMatrizRiesgos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(J822tNivelRiesgoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collJ825tMatrizRiesgos === null) {
			if ($this->isNew()) {
			   $this->collJ825tMatrizRiesgos = array();
			} else {

				$criteria->add(J825tMatrizRiesgoPeer::CO_RIESGO, $this->co_nivel_riesgo);

				J825tMatrizRiesgoPeer::addSelectColumns($criteria);
				$this->collJ825tMatrizRiesgos = J825tMatrizRiesgoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(J825tMatrizRiesgoPeer::CO_RIESGO, $this->co_nivel_riesgo);

				J825tMatrizRiesgoPeer::addSelectColumns($criteria);
				if (!isset($this->lastJ825tMatrizRiesgoCriteria) || !$this->lastJ825tMatrizRiesgoCriteria->equals($criteria)) {
					$this->collJ825tMatrizRiesgos = J825tMatrizRiesgoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastJ825tMatrizRiesgoCriteria = $criteria;
		return $this->collJ825tMatrizRiesgos;
	}

	/**
	 * Returns the number of related J825tMatrizRiesgo objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related J825tMatrizRiesgo objects.
	 * @throws     PropelException
	 */
	public function countJ825tMatrizRiesgos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(J822tNivelRiesgoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collJ825tMatrizRiesgos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(J825tMatrizRiesgoPeer::CO_RIESGO, $this->co_nivel_riesgo);

				$count = J825tMatrizRiesgoPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(J825tMatrizRiesgoPeer::CO_RIESGO, $this->co_nivel_riesgo);

				if (!isset($this->lastJ825tMatrizRiesgoCriteria) || !$this->lastJ825tMatrizRiesgoCriteria->equals($criteria)) {
					$count = J825tMatrizRiesgoPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collJ825tMatrizRiesgos);
				}
			} else {
				$count = count($this->collJ825tMatrizRiesgos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a J825tMatrizRiesgo object to this object
	 * through the J825tMatrizRiesgo foreign key attribute.
	 *
	 * @param      J825tMatrizRiesgo $l J825tMatrizRiesgo
	 * @return     void
	 * @throws     PropelException
	 */
	public function addJ825tMatrizRiesgo(J825tMatrizRiesgo $l)
	{
		if ($this->collJ825tMatrizRiesgos === null) {
			$this->initJ825tMatrizRiesgos();
		}
		if (!in_array($l, $this->collJ825tMatrizRiesgos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collJ825tMatrizRiesgos, $l);
			$l->setJ822tNivelRiesgo($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this J822tNivelRiesgo is new, it will return
	 * an empty collection; or if this J822tNivelRiesgo has previously
	 * been saved, it will retrieve related J825tMatrizRiesgos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in J822tNivelRiesgo.
	 */
	public function getJ825tMatrizRiesgosJoinJ823tNivelImpacto($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(J822tNivelRiesgoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collJ825tMatrizRiesgos === null) {
			if ($this->isNew()) {
				$this->collJ825tMatrizRiesgos = array();
			} else {

				$criteria->add(J825tMatrizRiesgoPeer::CO_RIESGO, $this->co_nivel_riesgo);

				$this->collJ825tMatrizRiesgos = J825tMatrizRiesgoPeer::doSelectJoinJ823tNivelImpacto($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(J825tMatrizRiesgoPeer::CO_RIESGO, $this->co_nivel_riesgo);

			if (!isset($this->lastJ825tMatrizRiesgoCriteria) || !$this->lastJ825tMatrizRiesgoCriteria->equals($criteria)) {
				$this->collJ825tMatrizRiesgos = J825tMatrizRiesgoPeer::doSelectJoinJ823tNivelImpacto($criteria, $con, $join_behavior);
			}
		}
		$this->lastJ825tMatrizRiesgoCriteria = $criteria;

		return $this->collJ825tMatrizRiesgos;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this J822tNivelRiesgo is new, it will return
	 * an empty collection; or if this J822tNivelRiesgo has previously
	 * been saved, it will retrieve related J825tMatrizRiesgos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in J822tNivelRiesgo.
	 */
	public function getJ825tMatrizRiesgosJoinJ824tNivelAmenaza($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(J822tNivelRiesgoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collJ825tMatrizRiesgos === null) {
			if ($this->isNew()) {
				$this->collJ825tMatrizRiesgos = array();
			} else {

				$criteria->add(J825tMatrizRiesgoPeer::CO_RIESGO, $this->co_nivel_riesgo);

				$this->collJ825tMatrizRiesgos = J825tMatrizRiesgoPeer::doSelectJoinJ824tNivelAmenaza($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(J825tMatrizRiesgoPeer::CO_RIESGO, $this->co_nivel_riesgo);

			if (!isset($this->lastJ825tMatrizRiesgoCriteria) || !$this->lastJ825tMatrizRiesgoCriteria->equals($criteria)) {
				$this->collJ825tMatrizRiesgos = J825tMatrizRiesgoPeer::doSelectJoinJ824tNivelAmenaza($criteria, $con, $join_behavior);
			}
		}
		$this->lastJ825tMatrizRiesgoCriteria = $criteria;

		return $this->collJ825tMatrizRiesgos;
	}

	/**
	 * Clears out the collJ827tTipoRiesgos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addJ827tTipoRiesgos()
	 */
	public function clearJ827tTipoRiesgos()
	{
		$this->collJ827tTipoRiesgos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collJ827tTipoRiesgos collection (array).
	 *
	 * By default this just sets the collJ827tTipoRiesgos collection to an empty array (like clearcollJ827tTipoRiesgos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initJ827tTipoRiesgos()
	{
		$this->collJ827tTipoRiesgos = array();
	}

	/**
	 * Gets an array of J827tTipoRiesgo objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this J822tNivelRiesgo has previously been saved, it will retrieve
	 * related J827tTipoRiesgos from storage. If this J822tNivelRiesgo is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array J827tTipoRiesgo[]
	 * @throws     PropelException
	 */
	public function getJ827tTipoRiesgos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(J822tNivelRiesgoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collJ827tTipoRiesgos === null) {
			if ($this->isNew()) {
			   $this->collJ827tTipoRiesgos = array();
			} else {

				$criteria->add(J827tTipoRiesgoPeer::CO_VALOR_RIESGO, $this->co_nivel_riesgo);

				J827tTipoRiesgoPeer::addSelectColumns($criteria);
				$this->collJ827tTipoRiesgos = J827tTipoRiesgoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(J827tTipoRiesgoPeer::CO_VALOR_RIESGO, $this->co_nivel_riesgo);

				J827tTipoRiesgoPeer::addSelectColumns($criteria);
				if (!isset($this->lastJ827tTipoRiesgoCriteria) || !$this->lastJ827tTipoRiesgoCriteria->equals($criteria)) {
					$this->collJ827tTipoRiesgos = J827tTipoRiesgoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastJ827tTipoRiesgoCriteria = $criteria;
		return $this->collJ827tTipoRiesgos;
	}

	/**
	 * Returns the number of related J827tTipoRiesgo objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related J827tTipoRiesgo objects.
	 * @throws     PropelException
	 */
	public function countJ827tTipoRiesgos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(J822tNivelRiesgoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collJ827tTipoRiesgos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(J827tTipoRiesgoPeer::CO_VALOR_RIESGO, $this->co_nivel_riesgo);

				$count = J827tTipoRiesgoPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(J827tTipoRiesgoPeer::CO_VALOR_RIESGO, $this->co_nivel_riesgo);

				if (!isset($this->lastJ827tTipoRiesgoCriteria) || !$this->lastJ827tTipoRiesgoCriteria->equals($criteria)) {
					$count = J827tTipoRiesgoPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collJ827tTipoRiesgos);
				}
			} else {
				$count = count($this->collJ827tTipoRiesgos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a J827tTipoRiesgo object to this object
	 * through the J827tTipoRiesgo foreign key attribute.
	 *
	 * @param      J827tTipoRiesgo $l J827tTipoRiesgo
	 * @return     void
	 * @throws     PropelException
	 */
	public function addJ827tTipoRiesgo(J827tTipoRiesgo $l)
	{
		if ($this->collJ827tTipoRiesgos === null) {
			$this->initJ827tTipoRiesgos();
		}
		if (!in_array($l, $this->collJ827tTipoRiesgos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collJ827tTipoRiesgos, $l);
			$l->setJ822tNivelRiesgo($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collJ825tMatrizRiesgos) {
				foreach ((array) $this->collJ825tMatrizRiesgos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collJ827tTipoRiesgos) {
				foreach ((array) $this->collJ827tTipoRiesgos as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collJ825tMatrizRiesgos = null;
		$this->collJ827tTipoRiesgos = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseJ822tNivelRiesgo:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseJ822tNivelRiesgo::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseJ822tNivelRiesgo
