<?php

/**
 * Base class that represents a row from the 'j004t_estado_forense' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Nov 14 07:33:32 2015
 *
 * @package    lib.model.om
 */
abstract class BaseJ004tEstadoForense extends BaseObject  implements Persistent {


  const PEER = 'J004tEstadoForensePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        J004tEstadoForensePeer
	 */
	protected static $peer;

	/**
	 * The value for the co_estado_forense field.
	 * @var        string
	 */
	protected $co_estado_forense;

	/**
	 * The value for the tx_descripcion field.
	 * @var        string
	 */
	protected $tx_descripcion;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the update_at field.
	 * @var        string
	 */
	protected $update_at;

	/**
	 * The value for the co_transaccion field.
	 * @var        string
	 */
	protected $co_transaccion;

	/**
	 * @var        C801tTransaccion
	 */
	protected $aC801tTransaccion;

	/**
	 * @var        array C001tForense[] Collection to store aggregation of C001tForense objects.
	 */
	protected $collC001tForenses;

	/**
	 * @var        Criteria The criteria used to select the current contents of collC001tForenses.
	 */
	private $lastC001tForenseCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseJ004tEstadoForense object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [co_estado_forense] column value.
	 * 
	 * @return     string
	 */
	public function getCoEstadoForense()
	{
		return $this->co_estado_forense;
	}

	/**
	 * Get the [tx_descripcion] column value.
	 * 
	 * @return     string
	 */
	public function getTxDescripcion()
	{
		return $this->tx_descripcion;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [update_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdateAt($format = 'Y-m-d H:i:s')
	{
		if ($this->update_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->update_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->update_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [co_transaccion] column value.
	 * 
	 * @return     string
	 */
	public function getCoTransaccion()
	{
		return $this->co_transaccion;
	}

	/**
	 * Set the value of [co_estado_forense] column.
	 * 
	 * @param      string $v new value
	 * @return     J004tEstadoForense The current object (for fluent API support)
	 */
	public function setCoEstadoForense($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_estado_forense !== $v) {
			$this->co_estado_forense = $v;
			$this->modifiedColumns[] = J004tEstadoForensePeer::CO_ESTADO_FORENSE;
		}

		return $this;
	} // setCoEstadoForense()

	/**
	 * Set the value of [tx_descripcion] column.
	 * 
	 * @param      string $v new value
	 * @return     J004tEstadoForense The current object (for fluent API support)
	 */
	public function setTxDescripcion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_descripcion !== $v) {
			$this->tx_descripcion = $v;
			$this->modifiedColumns[] = J004tEstadoForensePeer::TX_DESCRIPCION;
		}

		return $this;
	} // setTxDescripcion()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     J004tEstadoForense The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = J004tEstadoForensePeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [update_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     J004tEstadoForense The current object (for fluent API support)
	 */
	public function setUpdateAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->update_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->update_at !== null && $tmpDt = new DateTime($this->update_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->update_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = J004tEstadoForensePeer::UPDATE_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdateAt()

	/**
	 * Set the value of [co_transaccion] column.
	 * 
	 * @param      string $v new value
	 * @return     J004tEstadoForense The current object (for fluent API support)
	 */
	public function setCoTransaccion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_transaccion !== $v) {
			$this->co_transaccion = $v;
			$this->modifiedColumns[] = J004tEstadoForensePeer::CO_TRANSACCION;
		}

		if ($this->aC801tTransaccion !== null && $this->aC801tTransaccion->getCoTransaccion() !== $v) {
			$this->aC801tTransaccion = null;
		}

		return $this;
	} // setCoTransaccion()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->co_estado_forense = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->tx_descripcion = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->created_at = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->update_at = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->co_transaccion = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 5; // 5 = J004tEstadoForensePeer::NUM_COLUMNS - J004tEstadoForensePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating J004tEstadoForense object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aC801tTransaccion !== null && $this->co_transaccion !== $this->aC801tTransaccion->getCoTransaccion()) {
			$this->aC801tTransaccion = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(J004tEstadoForensePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = J004tEstadoForensePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aC801tTransaccion = null;
			$this->collC001tForenses = null;
			$this->lastC001tForenseCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseJ004tEstadoForense:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(J004tEstadoForensePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			J004tEstadoForensePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseJ004tEstadoForense:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseJ004tEstadoForense:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(J004tEstadoForensePeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(J004tEstadoForensePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseJ004tEstadoForense:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			J004tEstadoForensePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aC801tTransaccion !== null) {
				if ($this->aC801tTransaccion->isModified() || $this->aC801tTransaccion->isNew()) {
					$affectedRows += $this->aC801tTransaccion->save($con);
				}
				$this->setC801tTransaccion($this->aC801tTransaccion);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = J004tEstadoForensePeer::CO_ESTADO_FORENSE;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = J004tEstadoForensePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setCoEstadoForense($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += J004tEstadoForensePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collC001tForenses !== null) {
				foreach ($this->collC001tForenses as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aC801tTransaccion !== null) {
				if (!$this->aC801tTransaccion->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aC801tTransaccion->getValidationFailures());
				}
			}


			if (($retval = J004tEstadoForensePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collC001tForenses !== null) {
					foreach ($this->collC001tForenses as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = J004tEstadoForensePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getCoEstadoForense();
				break;
			case 1:
				return $this->getTxDescripcion();
				break;
			case 2:
				return $this->getCreatedAt();
				break;
			case 3:
				return $this->getUpdateAt();
				break;
			case 4:
				return $this->getCoTransaccion();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = J004tEstadoForensePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getCoEstadoForense(),
			$keys[1] => $this->getTxDescripcion(),
			$keys[2] => $this->getCreatedAt(),
			$keys[3] => $this->getUpdateAt(),
			$keys[4] => $this->getCoTransaccion(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = J004tEstadoForensePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setCoEstadoForense($value);
				break;
			case 1:
				$this->setTxDescripcion($value);
				break;
			case 2:
				$this->setCreatedAt($value);
				break;
			case 3:
				$this->setUpdateAt($value);
				break;
			case 4:
				$this->setCoTransaccion($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = J004tEstadoForensePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setCoEstadoForense($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setTxDescripcion($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCreatedAt($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setUpdateAt($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setCoTransaccion($arr[$keys[4]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(J004tEstadoForensePeer::DATABASE_NAME);

		if ($this->isColumnModified(J004tEstadoForensePeer::CO_ESTADO_FORENSE)) $criteria->add(J004tEstadoForensePeer::CO_ESTADO_FORENSE, $this->co_estado_forense);
		if ($this->isColumnModified(J004tEstadoForensePeer::TX_DESCRIPCION)) $criteria->add(J004tEstadoForensePeer::TX_DESCRIPCION, $this->tx_descripcion);
		if ($this->isColumnModified(J004tEstadoForensePeer::CREATED_AT)) $criteria->add(J004tEstadoForensePeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(J004tEstadoForensePeer::UPDATE_AT)) $criteria->add(J004tEstadoForensePeer::UPDATE_AT, $this->update_at);
		if ($this->isColumnModified(J004tEstadoForensePeer::CO_TRANSACCION)) $criteria->add(J004tEstadoForensePeer::CO_TRANSACCION, $this->co_transaccion);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(J004tEstadoForensePeer::DATABASE_NAME);

		$criteria->add(J004tEstadoForensePeer::CO_ESTADO_FORENSE, $this->co_estado_forense);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getCoEstadoForense();
	}

	/**
	 * Generic method to set the primary key (co_estado_forense column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setCoEstadoForense($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of J004tEstadoForense (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setTxDescripcion($this->tx_descripcion);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdateAt($this->update_at);

		$copyObj->setCoTransaccion($this->co_transaccion);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getC001tForenses() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addC001tForense($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setCoEstadoForense(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     J004tEstadoForense Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     J004tEstadoForensePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new J004tEstadoForensePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a C801tTransaccion object.
	 *
	 * @param      C801tTransaccion $v
	 * @return     J004tEstadoForense The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setC801tTransaccion(C801tTransaccion $v = null)
	{
		if ($v === null) {
			$this->setCoTransaccion(NULL);
		} else {
			$this->setCoTransaccion($v->getCoTransaccion());
		}

		$this->aC801tTransaccion = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the C801tTransaccion object, it will not be re-added.
		if ($v !== null) {
			$v->addJ004tEstadoForense($this);
		}

		return $this;
	}


	/**
	 * Get the associated C801tTransaccion object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     C801tTransaccion The associated C801tTransaccion object.
	 * @throws     PropelException
	 */
	public function getC801tTransaccion(PropelPDO $con = null)
	{
		if ($this->aC801tTransaccion === null && (($this->co_transaccion !== "" && $this->co_transaccion !== null))) {
			$c = new Criteria(C801tTransaccionPeer::DATABASE_NAME);
			$c->add(C801tTransaccionPeer::CO_TRANSACCION, $this->co_transaccion);
			$this->aC801tTransaccion = C801tTransaccionPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aC801tTransaccion->addJ004tEstadoForenses($this);
			 */
		}
		return $this->aC801tTransaccion;
	}

	/**
	 * Clears out the collC001tForenses collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addC001tForenses()
	 */
	public function clearC001tForenses()
	{
		$this->collC001tForenses = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collC001tForenses collection (array).
	 *
	 * By default this just sets the collC001tForenses collection to an empty array (like clearcollC001tForenses());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initC001tForenses()
	{
		$this->collC001tForenses = array();
	}

	/**
	 * Gets an array of C001tForense objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this J004tEstadoForense has previously been saved, it will retrieve
	 * related C001tForenses from storage. If this J004tEstadoForense is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array C001tForense[]
	 * @throws     PropelException
	 */
	public function getC001tForenses($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(J004tEstadoForensePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collC001tForenses === null) {
			if ($this->isNew()) {
			   $this->collC001tForenses = array();
			} else {

				$criteria->add(C001tForensePeer::CO_ESTADO_FORENSE, $this->co_estado_forense);

				C001tForensePeer::addSelectColumns($criteria);
				$this->collC001tForenses = C001tForensePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(C001tForensePeer::CO_ESTADO_FORENSE, $this->co_estado_forense);

				C001tForensePeer::addSelectColumns($criteria);
				if (!isset($this->lastC001tForenseCriteria) || !$this->lastC001tForenseCriteria->equals($criteria)) {
					$this->collC001tForenses = C001tForensePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastC001tForenseCriteria = $criteria;
		return $this->collC001tForenses;
	}

	/**
	 * Returns the number of related C001tForense objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related C001tForense objects.
	 * @throws     PropelException
	 */
	public function countC001tForenses(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(J004tEstadoForensePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collC001tForenses === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(C001tForensePeer::CO_ESTADO_FORENSE, $this->co_estado_forense);

				$count = C001tForensePeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(C001tForensePeer::CO_ESTADO_FORENSE, $this->co_estado_forense);

				if (!isset($this->lastC001tForenseCriteria) || !$this->lastC001tForenseCriteria->equals($criteria)) {
					$count = C001tForensePeer::doCount($criteria, $con);
				} else {
					$count = count($this->collC001tForenses);
				}
			} else {
				$count = count($this->collC001tForenses);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a C001tForense object to this object
	 * through the C001tForense foreign key attribute.
	 *
	 * @param      C001tForense $l C001tForense
	 * @return     void
	 * @throws     PropelException
	 */
	public function addC001tForense(C001tForense $l)
	{
		if ($this->collC001tForenses === null) {
			$this->initC001tForenses();
		}
		if (!in_array($l, $this->collC001tForenses, true)) { // only add it if the **same** object is not already associated
			array_push($this->collC001tForenses, $l);
			$l->setJ004tEstadoForense($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this J004tEstadoForense is new, it will return
	 * an empty collection; or if this J004tEstadoForense has previously
	 * been saved, it will retrieve related C001tForenses from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in J004tEstadoForense.
	 */
	public function getC001tForensesJoinJ813tRegion($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(J004tEstadoForensePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collC001tForenses === null) {
			if ($this->isNew()) {
				$this->collC001tForenses = array();
			} else {

				$criteria->add(C001tForensePeer::CO_ESTADO_FORENSE, $this->co_estado_forense);

				$this->collC001tForenses = C001tForensePeer::doSelectJoinJ813tRegion($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(C001tForensePeer::CO_ESTADO_FORENSE, $this->co_estado_forense);

			if (!isset($this->lastC001tForenseCriteria) || !$this->lastC001tForenseCriteria->equals($criteria)) {
				$this->collC001tForenses = C001tForensePeer::doSelectJoinJ813tRegion($criteria, $con, $join_behavior);
			}
		}
		$this->lastC001tForenseCriteria = $criteria;

		return $this->collC001tForenses;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this J004tEstadoForense is new, it will return
	 * an empty collection; or if this J004tEstadoForense has previously
	 * been saved, it will retrieve related C001tForenses from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in J004tEstadoForense.
	 */
	public function getC001tForensesJoinJ814tNegocio($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(J004tEstadoForensePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collC001tForenses === null) {
			if ($this->isNew()) {
				$this->collC001tForenses = array();
			} else {

				$criteria->add(C001tForensePeer::CO_ESTADO_FORENSE, $this->co_estado_forense);

				$this->collC001tForenses = C001tForensePeer::doSelectJoinJ814tNegocio($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(C001tForensePeer::CO_ESTADO_FORENSE, $this->co_estado_forense);

			if (!isset($this->lastC001tForenseCriteria) || !$this->lastC001tForenseCriteria->equals($criteria)) {
				$this->collC001tForenses = C001tForensePeer::doSelectJoinJ814tNegocio($criteria, $con, $join_behavior);
			}
		}
		$this->lastC001tForenseCriteria = $criteria;

		return $this->collC001tForenses;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this J004tEstadoForense is new, it will return
	 * an empty collection; or if this J004tEstadoForense has previously
	 * been saved, it will retrieve related C001tForenses from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in J004tEstadoForense.
	 */
	public function getC001tForensesJoinJ815tDivision($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(J004tEstadoForensePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collC001tForenses === null) {
			if ($this->isNew()) {
				$this->collC001tForenses = array();
			} else {

				$criteria->add(C001tForensePeer::CO_ESTADO_FORENSE, $this->co_estado_forense);

				$this->collC001tForenses = C001tForensePeer::doSelectJoinJ815tDivision($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(C001tForensePeer::CO_ESTADO_FORENSE, $this->co_estado_forense);

			if (!isset($this->lastC001tForenseCriteria) || !$this->lastC001tForenseCriteria->equals($criteria)) {
				$this->collC001tForenses = C001tForensePeer::doSelectJoinJ815tDivision($criteria, $con, $join_behavior);
			}
		}
		$this->lastC001tForenseCriteria = $criteria;

		return $this->collC001tForenses;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this J004tEstadoForense is new, it will return
	 * an empty collection; or if this J004tEstadoForense has previously
	 * been saved, it will retrieve related C001tForenses from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in J004tEstadoForense.
	 */
	public function getC001tForensesJoinJ001tAlcanceForense($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(J004tEstadoForensePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collC001tForenses === null) {
			if ($this->isNew()) {
				$this->collC001tForenses = array();
			} else {

				$criteria->add(C001tForensePeer::CO_ESTADO_FORENSE, $this->co_estado_forense);

				$this->collC001tForenses = C001tForensePeer::doSelectJoinJ001tAlcanceForense($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(C001tForensePeer::CO_ESTADO_FORENSE, $this->co_estado_forense);

			if (!isset($this->lastC001tForenseCriteria) || !$this->lastC001tForenseCriteria->equals($criteria)) {
				$this->collC001tForenses = C001tForensePeer::doSelectJoinJ001tAlcanceForense($criteria, $con, $join_behavior);
			}
		}
		$this->lastC001tForenseCriteria = $criteria;

		return $this->collC001tForenses;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this J004tEstadoForense is new, it will return
	 * an empty collection; or if this J004tEstadoForense has previously
	 * been saved, it will retrieve related C001tForenses from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in J004tEstadoForense.
	 */
	public function getC001tForensesJoinC801tTransaccion($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(J004tEstadoForensePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collC001tForenses === null) {
			if ($this->isNew()) {
				$this->collC001tForenses = array();
			} else {

				$criteria->add(C001tForensePeer::CO_ESTADO_FORENSE, $this->co_estado_forense);

				$this->collC001tForenses = C001tForensePeer::doSelectJoinC801tTransaccion($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(C001tForensePeer::CO_ESTADO_FORENSE, $this->co_estado_forense);

			if (!isset($this->lastC001tForenseCriteria) || !$this->lastC001tForenseCriteria->equals($criteria)) {
				$this->collC001tForenses = C001tForensePeer::doSelectJoinC801tTransaccion($criteria, $con, $join_behavior);
			}
		}
		$this->lastC001tForenseCriteria = $criteria;

		return $this->collC001tForenses;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this J004tEstadoForense is new, it will return
	 * an empty collection; or if this J004tEstadoForense has previously
	 * been saved, it will retrieve related C001tForenses from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in J004tEstadoForense.
	 */
	public function getC001tForensesJoinJ802tClasificacion($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(J004tEstadoForensePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collC001tForenses === null) {
			if ($this->isNew()) {
				$this->collC001tForenses = array();
			} else {

				$criteria->add(C001tForensePeer::CO_ESTADO_FORENSE, $this->co_estado_forense);

				$this->collC001tForenses = C001tForensePeer::doSelectJoinJ802tClasificacion($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(C001tForensePeer::CO_ESTADO_FORENSE, $this->co_estado_forense);

			if (!isset($this->lastC001tForenseCriteria) || !$this->lastC001tForenseCriteria->equals($criteria)) {
				$this->collC001tForenses = C001tForensePeer::doSelectJoinJ802tClasificacion($criteria, $con, $join_behavior);
			}
		}
		$this->lastC001tForenseCriteria = $criteria;

		return $this->collC001tForenses;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collC001tForenses) {
				foreach ((array) $this->collC001tForenses as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collC001tForenses = null;
			$this->aC801tTransaccion = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseJ004tEstadoForense:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseJ004tEstadoForense::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseJ004tEstadoForense
