<?php

/**
 * Base class that represents a row from the 'j007t_repositorio_digital' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Nov 14 07:33:32 2015
 *
 * @package    lib.model.om
 */
abstract class BaseJ007tRepositorioDigital extends BaseObject  implements Persistent {


  const PEER = 'J007tRepositorioDigitalPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        J007tRepositorioDigitalPeer
	 */
	protected static $peer;

	/**
	 * The value for the co_repositorio_digital field.
	 * @var        string
	 */
	protected $co_repositorio_digital;

	/**
	 * The value for the tx_titulo field.
	 * @var        string
	 */
	protected $tx_titulo;

	/**
	 * The value for the tx_direccion_ip field.
	 * @var        string
	 */
	protected $tx_direccion_ip;

	/**
	 * The value for the co_gerencia field.
	 * @var        string
	 */
	protected $co_gerencia;

	/**
	 * The value for the co_custodio field.
	 * @var        string
	 */
	protected $co_custodio;

	/**
	 * The value for the tx_observaciones field.
	 * @var        string
	 */
	protected $tx_observaciones;

	/**
	 * The value for the co_clasificacion field.
	 * @var        string
	 */
	protected $co_clasificacion;

	/**
	 * The value for the co_transaccion field.
	 * @var        string
	 */
	protected $co_transaccion;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the update_at field.
	 * @var        string
	 */
	protected $update_at;

	/**
	 * @var        J804tGerencia
	 */
	protected $aJ804tGerencia;

	/**
	 * @var        J812Persona
	 */
	protected $aJ812Persona;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseJ007tRepositorioDigital object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [co_repositorio_digital] column value.
	 * 
	 * @return     string
	 */
	public function getCoRepositorioDigital()
	{
		return $this->co_repositorio_digital;
	}

	/**
	 * Get the [tx_titulo] column value.
	 * 
	 * @return     string
	 */
	public function getTxTitulo()
	{
		return $this->tx_titulo;
	}

	/**
	 * Get the [tx_direccion_ip] column value.
	 * 
	 * @return     string
	 */
	public function getTxDireccionIp()
	{
		return $this->tx_direccion_ip;
	}

	/**
	 * Get the [co_gerencia] column value.
	 * 
	 * @return     string
	 */
	public function getCoGerencia()
	{
		return $this->co_gerencia;
	}

	/**
	 * Get the [co_custodio] column value.
	 * 
	 * @return     string
	 */
	public function getCoCustodio()
	{
		return $this->co_custodio;
	}

	/**
	 * Get the [tx_observaciones] column value.
	 * 
	 * @return     string
	 */
	public function getTxObservaciones()
	{
		return $this->tx_observaciones;
	}

	/**
	 * Get the [co_clasificacion] column value.
	 * 
	 * @return     string
	 */
	public function getCoClasificacion()
	{
		return $this->co_clasificacion;
	}

	/**
	 * Get the [co_transaccion] column value.
	 * 
	 * @return     string
	 */
	public function getCoTransaccion()
	{
		return $this->co_transaccion;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [update_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdateAt($format = 'Y-m-d H:i:s')
	{
		if ($this->update_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->update_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->update_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [co_repositorio_digital] column.
	 * 
	 * @param      string $v new value
	 * @return     J007tRepositorioDigital The current object (for fluent API support)
	 */
	public function setCoRepositorioDigital($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_repositorio_digital !== $v) {
			$this->co_repositorio_digital = $v;
			$this->modifiedColumns[] = J007tRepositorioDigitalPeer::CO_REPOSITORIO_DIGITAL;
		}

		return $this;
	} // setCoRepositorioDigital()

	/**
	 * Set the value of [tx_titulo] column.
	 * 
	 * @param      string $v new value
	 * @return     J007tRepositorioDigital The current object (for fluent API support)
	 */
	public function setTxTitulo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_titulo !== $v) {
			$this->tx_titulo = $v;
			$this->modifiedColumns[] = J007tRepositorioDigitalPeer::TX_TITULO;
		}

		return $this;
	} // setTxTitulo()

	/**
	 * Set the value of [tx_direccion_ip] column.
	 * 
	 * @param      string $v new value
	 * @return     J007tRepositorioDigital The current object (for fluent API support)
	 */
	public function setTxDireccionIp($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_direccion_ip !== $v) {
			$this->tx_direccion_ip = $v;
			$this->modifiedColumns[] = J007tRepositorioDigitalPeer::TX_DIRECCION_IP;
		}

		return $this;
	} // setTxDireccionIp()

	/**
	 * Set the value of [co_gerencia] column.
	 * 
	 * @param      string $v new value
	 * @return     J007tRepositorioDigital The current object (for fluent API support)
	 */
	public function setCoGerencia($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_gerencia !== $v) {
			$this->co_gerencia = $v;
			$this->modifiedColumns[] = J007tRepositorioDigitalPeer::CO_GERENCIA;
		}

		if ($this->aJ804tGerencia !== null && $this->aJ804tGerencia->getCoGerencia() !== $v) {
			$this->aJ804tGerencia = null;
		}

		return $this;
	} // setCoGerencia()

	/**
	 * Set the value of [co_custodio] column.
	 * 
	 * @param      string $v new value
	 * @return     J007tRepositorioDigital The current object (for fluent API support)
	 */
	public function setCoCustodio($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_custodio !== $v) {
			$this->co_custodio = $v;
			$this->modifiedColumns[] = J007tRepositorioDigitalPeer::CO_CUSTODIO;
		}

		if ($this->aJ812Persona !== null && $this->aJ812Persona->getCoPersona() !== $v) {
			$this->aJ812Persona = null;
		}

		return $this;
	} // setCoCustodio()

	/**
	 * Set the value of [tx_observaciones] column.
	 * 
	 * @param      string $v new value
	 * @return     J007tRepositorioDigital The current object (for fluent API support)
	 */
	public function setTxObservaciones($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_observaciones !== $v) {
			$this->tx_observaciones = $v;
			$this->modifiedColumns[] = J007tRepositorioDigitalPeer::TX_OBSERVACIONES;
		}

		return $this;
	} // setTxObservaciones()

	/**
	 * Set the value of [co_clasificacion] column.
	 * 
	 * @param      string $v new value
	 * @return     J007tRepositorioDigital The current object (for fluent API support)
	 */
	public function setCoClasificacion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_clasificacion !== $v) {
			$this->co_clasificacion = $v;
			$this->modifiedColumns[] = J007tRepositorioDigitalPeer::CO_CLASIFICACION;
		}

		return $this;
	} // setCoClasificacion()

	/**
	 * Set the value of [co_transaccion] column.
	 * 
	 * @param      string $v new value
	 * @return     J007tRepositorioDigital The current object (for fluent API support)
	 */
	public function setCoTransaccion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_transaccion !== $v) {
			$this->co_transaccion = $v;
			$this->modifiedColumns[] = J007tRepositorioDigitalPeer::CO_TRANSACCION;
		}

		return $this;
	} // setCoTransaccion()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     J007tRepositorioDigital The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = J007tRepositorioDigitalPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [update_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     J007tRepositorioDigital The current object (for fluent API support)
	 */
	public function setUpdateAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->update_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->update_at !== null && $tmpDt = new DateTime($this->update_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->update_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = J007tRepositorioDigitalPeer::UPDATE_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdateAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->co_repositorio_digital = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->tx_titulo = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->tx_direccion_ip = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->co_gerencia = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->co_custodio = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->tx_observaciones = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->co_clasificacion = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->co_transaccion = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->created_at = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->update_at = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 10; // 10 = J007tRepositorioDigitalPeer::NUM_COLUMNS - J007tRepositorioDigitalPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating J007tRepositorioDigital object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aJ804tGerencia !== null && $this->co_gerencia !== $this->aJ804tGerencia->getCoGerencia()) {
			$this->aJ804tGerencia = null;
		}
		if ($this->aJ812Persona !== null && $this->co_custodio !== $this->aJ812Persona->getCoPersona()) {
			$this->aJ812Persona = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(J007tRepositorioDigitalPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = J007tRepositorioDigitalPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aJ804tGerencia = null;
			$this->aJ812Persona = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseJ007tRepositorioDigital:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(J007tRepositorioDigitalPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			J007tRepositorioDigitalPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseJ007tRepositorioDigital:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseJ007tRepositorioDigital:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(J007tRepositorioDigitalPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(J007tRepositorioDigitalPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseJ007tRepositorioDigital:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			J007tRepositorioDigitalPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aJ804tGerencia !== null) {
				if ($this->aJ804tGerencia->isModified() || $this->aJ804tGerencia->isNew()) {
					$affectedRows += $this->aJ804tGerencia->save($con);
				}
				$this->setJ804tGerencia($this->aJ804tGerencia);
			}

			if ($this->aJ812Persona !== null) {
				if ($this->aJ812Persona->isModified() || $this->aJ812Persona->isNew()) {
					$affectedRows += $this->aJ812Persona->save($con);
				}
				$this->setJ812Persona($this->aJ812Persona);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = J007tRepositorioDigitalPeer::CO_REPOSITORIO_DIGITAL;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = J007tRepositorioDigitalPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setCoRepositorioDigital($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += J007tRepositorioDigitalPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aJ804tGerencia !== null) {
				if (!$this->aJ804tGerencia->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJ804tGerencia->getValidationFailures());
				}
			}

			if ($this->aJ812Persona !== null) {
				if (!$this->aJ812Persona->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJ812Persona->getValidationFailures());
				}
			}


			if (($retval = J007tRepositorioDigitalPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = J007tRepositorioDigitalPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getCoRepositorioDigital();
				break;
			case 1:
				return $this->getTxTitulo();
				break;
			case 2:
				return $this->getTxDireccionIp();
				break;
			case 3:
				return $this->getCoGerencia();
				break;
			case 4:
				return $this->getCoCustodio();
				break;
			case 5:
				return $this->getTxObservaciones();
				break;
			case 6:
				return $this->getCoClasificacion();
				break;
			case 7:
				return $this->getCoTransaccion();
				break;
			case 8:
				return $this->getCreatedAt();
				break;
			case 9:
				return $this->getUpdateAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = J007tRepositorioDigitalPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getCoRepositorioDigital(),
			$keys[1] => $this->getTxTitulo(),
			$keys[2] => $this->getTxDireccionIp(),
			$keys[3] => $this->getCoGerencia(),
			$keys[4] => $this->getCoCustodio(),
			$keys[5] => $this->getTxObservaciones(),
			$keys[6] => $this->getCoClasificacion(),
			$keys[7] => $this->getCoTransaccion(),
			$keys[8] => $this->getCreatedAt(),
			$keys[9] => $this->getUpdateAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = J007tRepositorioDigitalPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setCoRepositorioDigital($value);
				break;
			case 1:
				$this->setTxTitulo($value);
				break;
			case 2:
				$this->setTxDireccionIp($value);
				break;
			case 3:
				$this->setCoGerencia($value);
				break;
			case 4:
				$this->setCoCustodio($value);
				break;
			case 5:
				$this->setTxObservaciones($value);
				break;
			case 6:
				$this->setCoClasificacion($value);
				break;
			case 7:
				$this->setCoTransaccion($value);
				break;
			case 8:
				$this->setCreatedAt($value);
				break;
			case 9:
				$this->setUpdateAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = J007tRepositorioDigitalPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setCoRepositorioDigital($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setTxTitulo($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTxDireccionIp($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCoGerencia($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setCoCustodio($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setTxObservaciones($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCoClasificacion($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCoTransaccion($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setCreatedAt($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setUpdateAt($arr[$keys[9]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(J007tRepositorioDigitalPeer::DATABASE_NAME);

		if ($this->isColumnModified(J007tRepositorioDigitalPeer::CO_REPOSITORIO_DIGITAL)) $criteria->add(J007tRepositorioDigitalPeer::CO_REPOSITORIO_DIGITAL, $this->co_repositorio_digital);
		if ($this->isColumnModified(J007tRepositorioDigitalPeer::TX_TITULO)) $criteria->add(J007tRepositorioDigitalPeer::TX_TITULO, $this->tx_titulo);
		if ($this->isColumnModified(J007tRepositorioDigitalPeer::TX_DIRECCION_IP)) $criteria->add(J007tRepositorioDigitalPeer::TX_DIRECCION_IP, $this->tx_direccion_ip);
		if ($this->isColumnModified(J007tRepositorioDigitalPeer::CO_GERENCIA)) $criteria->add(J007tRepositorioDigitalPeer::CO_GERENCIA, $this->co_gerencia);
		if ($this->isColumnModified(J007tRepositorioDigitalPeer::CO_CUSTODIO)) $criteria->add(J007tRepositorioDigitalPeer::CO_CUSTODIO, $this->co_custodio);
		if ($this->isColumnModified(J007tRepositorioDigitalPeer::TX_OBSERVACIONES)) $criteria->add(J007tRepositorioDigitalPeer::TX_OBSERVACIONES, $this->tx_observaciones);
		if ($this->isColumnModified(J007tRepositorioDigitalPeer::CO_CLASIFICACION)) $criteria->add(J007tRepositorioDigitalPeer::CO_CLASIFICACION, $this->co_clasificacion);
		if ($this->isColumnModified(J007tRepositorioDigitalPeer::CO_TRANSACCION)) $criteria->add(J007tRepositorioDigitalPeer::CO_TRANSACCION, $this->co_transaccion);
		if ($this->isColumnModified(J007tRepositorioDigitalPeer::CREATED_AT)) $criteria->add(J007tRepositorioDigitalPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(J007tRepositorioDigitalPeer::UPDATE_AT)) $criteria->add(J007tRepositorioDigitalPeer::UPDATE_AT, $this->update_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(J007tRepositorioDigitalPeer::DATABASE_NAME);

		$criteria->add(J007tRepositorioDigitalPeer::CO_REPOSITORIO_DIGITAL, $this->co_repositorio_digital);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getCoRepositorioDigital();
	}

	/**
	 * Generic method to set the primary key (co_repositorio_digital column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setCoRepositorioDigital($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of J007tRepositorioDigital (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setTxTitulo($this->tx_titulo);

		$copyObj->setTxDireccionIp($this->tx_direccion_ip);

		$copyObj->setCoGerencia($this->co_gerencia);

		$copyObj->setCoCustodio($this->co_custodio);

		$copyObj->setTxObservaciones($this->tx_observaciones);

		$copyObj->setCoClasificacion($this->co_clasificacion);

		$copyObj->setCoTransaccion($this->co_transaccion);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdateAt($this->update_at);


		$copyObj->setNew(true);

		$copyObj->setCoRepositorioDigital(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     J007tRepositorioDigital Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     J007tRepositorioDigitalPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new J007tRepositorioDigitalPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a J804tGerencia object.
	 *
	 * @param      J804tGerencia $v
	 * @return     J007tRepositorioDigital The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJ804tGerencia(J804tGerencia $v = null)
	{
		if ($v === null) {
			$this->setCoGerencia(NULL);
		} else {
			$this->setCoGerencia($v->getCoGerencia());
		}

		$this->aJ804tGerencia = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the J804tGerencia object, it will not be re-added.
		if ($v !== null) {
			$v->addJ007tRepositorioDigital($this);
		}

		return $this;
	}


	/**
	 * Get the associated J804tGerencia object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     J804tGerencia The associated J804tGerencia object.
	 * @throws     PropelException
	 */
	public function getJ804tGerencia(PropelPDO $con = null)
	{
		if ($this->aJ804tGerencia === null && (($this->co_gerencia !== "" && $this->co_gerencia !== null))) {
			$c = new Criteria(J804tGerenciaPeer::DATABASE_NAME);
			$c->add(J804tGerenciaPeer::CO_GERENCIA, $this->co_gerencia);
			$this->aJ804tGerencia = J804tGerenciaPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJ804tGerencia->addJ007tRepositorioDigitals($this);
			 */
		}
		return $this->aJ804tGerencia;
	}

	/**
	 * Declares an association between this object and a J812Persona object.
	 *
	 * @param      J812Persona $v
	 * @return     J007tRepositorioDigital The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJ812Persona(J812Persona $v = null)
	{
		if ($v === null) {
			$this->setCoCustodio(NULL);
		} else {
			$this->setCoCustodio($v->getCoPersona());
		}

		$this->aJ812Persona = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the J812Persona object, it will not be re-added.
		if ($v !== null) {
			$v->addJ007tRepositorioDigital($this);
		}

		return $this;
	}


	/**
	 * Get the associated J812Persona object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     J812Persona The associated J812Persona object.
	 * @throws     PropelException
	 */
	public function getJ812Persona(PropelPDO $con = null)
	{
		if ($this->aJ812Persona === null && (($this->co_custodio !== "" && $this->co_custodio !== null))) {
			$c = new Criteria(J812PersonaPeer::DATABASE_NAME);
			$c->add(J812PersonaPeer::CO_PERSONA, $this->co_custodio);
			$this->aJ812Persona = J812PersonaPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJ812Persona->addJ007tRepositorioDigitals($this);
			 */
		}
		return $this->aJ812Persona;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aJ804tGerencia = null;
			$this->aJ812Persona = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseJ007tRepositorioDigital:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseJ007tRepositorioDigital::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseJ007tRepositorioDigital
