<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2015/11/16 14:51:12
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoJ813tRegion/actions/actions.class.php');

